package com.perso.T4C.mapping.definition;

import java.util.List;

public final class GroundMosaicDefinitions {
  private GroundMosaicDefinitions() {}

  public record Definition(String id, int width, int height, List<String> frames) {}

  public static List<Definition> all() {
    return List.of(
        new Definition("0x1", 13, 15, List.of("64kNormalGrass (&x, &y)")),
        new Definition("0x3", 10, 9, List.of("Ground_Water (&x, &y)")),
        new Definition("0x4", 10, 9, List.of("Ground_Water (&x, &y)")),
        new Definition("0x5", 11, 11, List.of("Grass (&x, &y)")),
        new Definition("0x6", 10, 9, List.of("Hardrock (&x, &y)")),
        new Definition("0x7", 11, 10, List.of("Dgrass (&x, &y)")),
        new Definition("0x9", 7, 6, List.of("DungeonRockFloor (&x, &y)")),
        new Definition("0xb", 11, 10, List.of("EarthTile (&x, &y)")),
        new Definition("0xc", 2, 2, List.of("Town Road Dale (&x, &y)")),
        new Definition("0xd", 3, 3, List.of("RockFloor (&x, &y)")),
        new Definition("0x11", 14, 14, List.of("CavernFloor (&x, &y)")),
        new Definition(
            "0x12",
            5,
            5,
            List.of(
                "Dtm4 1", "Dtm5 1", "Dtm1 1", "Dtm2 1", "Dtm3 1", "Dtm4 2", "Dtm5 2", "Dtm1 2",
                "Dtm2 2", "Dtm3 2", "Dtm4 3", "Dtm5 3", "Dtm1 3", "Dtm2 3", "Dtm3 3", "Dtm4 4",
                "Dtm5 4", "Dtm1 4", "Dtm2 4", "Dtm3 4", "Dtm4 5", "Dtm5 5", "Dtm1 5", "Dtm2 5",
                "Dtm3 5")),
        new Definition(
            "0x29",
            5,
            5,
            List.of(
                "Dtm1 2",
                "DungeonFloorTorch2 2",
                "DungeonFloorTorch3 2",
                "DungeonFloorTorch4 2",
                "DungeonFloorTorch5 2",
                "Dtm1 3",
                "Dtm2 3",
                "DungeonFloorTorch3 3",
                "DungeonFloorTorch4 3",
                "DungeonFloorTorch5 3",
                "Dtm1 4",
                "Dtm2 4",
                "Dtm3 4",
                "DungeonFloorTorch4 4",
                "DungeonFloorTorch5 4",
                "Dtm1 5",
                "Dtm2 5",
                "Dtm3 5",
                "Dtm4 5",
                "DungeonFloorTorch5 5",
                "DungeonFloorTorch1 1",
                "DungeonFloorTorch2 1",
                "DungeonFloorTorch3 1",
                "DungeonFloorTorch4 1",
                "DungeonFloorTorch5 1")),
        new Definition(
            "0x2a",
            5,
            5,
            List.of(
                "Dtm2 3",
                "DungeonFloorTorchLeft (2, 4)",
                "DungeonFloorTorchLeft (2, 5)",
                "Dtm2 1",
                "Dtm2 2",
                "DungeonFloorTorchLeft (3, 3)",
                "DungeonFloorTorchLeft (3, 4)",
                "DungeonFloorTorchLeft (3, 5)",
                "Dtm3 1",
                "Dtm3 2",
                "DungeonFloorTorchLeft (4, 3)",
                "DungeonFloorTorchLeft (4, 4)",
                "DungeonFloorTorchLeft (4, 5)",
                "Dtm4 1",
                "DungeonFloorTorchLeft (4, 2)",
                "DungeonFloorTorchLeft (5, 3)",
                "DungeonFloorTorchLeft (5, 4)",
                "DungeonFloorTorchLeft (5, 5)",
                "DungeonFloorTorchLeft (5, 1)",
                "DungeonFloorTorchLeft (5, 2)",
                "Dtm1 3",
                "Dtm1 4",
                "DungeonFloorTorchLeft (1, 5)",
                "Dtm1 1",
                "Dtm1 2")),
        new Definition(
            "0x2b",
            10,
            10,
            List.of(
                "DungeonFloorOverHeadLight1 (1, 1)",
                "DungeonFloorOverHeadLight1 (1, 2)",
                "DungeonFloorOverHeadLight1 (1, 3)",
                "DungeonFloorOverHeadLight1 (1, 4)",
                "DungeonFloorOverHeadLight1 (1, 5)",
                "DungeonFloorOverHeadLight1 (1, 6)",
                "DungeonFloorOverHeadLight1 (1, 7)",
                "DungeonFloorOverHeadLight1 (1, 8)",
                "DungeonFloorOverHeadLight1 (1, 9)",
                "DungeonFloorOverHeadLight1 (1, 10)",
                "DungeonFloorOverHeadLight1 (2, 1)",
                "DungeonFloorOverHeadLight1 (2, 2)",
                "DungeonFloorOverHeadLight1 (2, 3)",
                "DungeonFloorOverHeadLight1 (2, 4)",
                "DungeonFloorOverHeadLight1 (2, 5)",
                "DungeonFloorOverHeadLight1 (2, 6)",
                "DungeonFloorOverHeadLight1 (2, 7)",
                "DungeonFloorOverHeadLight1 (2, 8)",
                "DungeonFloorOverHeadLight1 (2, 9)",
                "DungeonFloorOverHeadLight1 (2, 10)",
                "DungeonFloorOverHeadLight1 (3, 1)",
                "DungeonFloorOverHeadLight1 (3, 2)",
                "DungeonFloorOverHeadLight1 (3, 3)",
                "DungeonFloorOverHeadLight1 (3, 4)",
                "DungeonFloorOverHeadLight1 (3, 5)",
                "DungeonFloorOverHeadLight1 (3, 6)",
                "DungeonFloorOverHeadLight1 (3, 7)",
                "DungeonFloorOverHeadLight1 (3, 8)",
                "DungeonFloorOverHeadLight1 (3, 9)",
                "DungeonFloorOverHeadLight1 (3, 10)",
                "DungeonFloorOverHeadLight1 (4, 1)",
                "DungeonFloorOverHeadLight1 (4, 2)",
                "DungeonFloorOverHeadLight1 (4, 3)",
                "DungeonFloorOverHeadLight1 (4, 4)",
                "DungeonFloorOverHeadLight1 (4, 5)",
                "DungeonFloorOverHeadLight1 (4, 6)",
                "DungeonFloorOverHeadLight1 (4, 7)",
                "DungeonFloorOverHeadLight1 (4, 8)",
                "DungeonFloorOverHeadLight1 (4, 9)",
                "DungeonFloorOverHeadLight1 (4, 10)",
                "DungeonFloorOverHeadLight1 (5, 1)",
                "DungeonFloorOverHeadLight1 (5, 2)",
                "DungeonFloorOverHeadLight1 (5, 3)",
                "DungeonFloorOverHeadLight1 (5, 4)",
                "DungeonFloorOverHeadLight1 (5, 5)",
                "DungeonFloorOverHeadLight1 (5, 6)",
                "DungeonFloorOverHeadLight1 (5, 7)",
                "DungeonFloorOverHeadLight1 (5, 8)",
                "DungeonFloorOverHeadLight1 (5, 9)",
                "DungeonFloorOverHeadLight1 (5, 10)",
                "DungeonFloorOverHeadLight1 (6, 1)",
                "DungeonFloorOverHeadLight1 (6, 2)",
                "DungeonFloorOverHeadLight1 (6, 3)",
                "DungeonFloorOverHeadLight1 (6, 4)",
                "DungeonFloorOverHeadLight1 (6, 5)",
                "DungeonFloorOverHeadLight1 (6, 6)",
                "DungeonFloorOverHeadLight1 (6, 7)",
                "DungeonFloorOverHeadLight1 (6, 8)",
                "DungeonFloorOverHeadLight1 (6, 9)",
                "DungeonFloorOverHeadLight1 (6, 10)",
                "DungeonFloorOverHeadLight1 (7, 1)",
                "DungeonFloorOverHeadLight1 (7, 2)",
                "DungeonFloorOverHeadLight1 (7, 3)",
                "DungeonFloorOverHeadLight1 (7, 4)",
                "DungeonFloorOverHeadLight1 (7, 5)",
                "DungeonFloorOverHeadLight1 (7, 6)",
                "DungeonFloorOverHeadLight1 (7, 7)",
                "DungeonFloorOverHeadLight1 (7, 8)",
                "DungeonFloorOverHeadLight1 (7, 9)",
                "DungeonFloorOverHeadLight1 (7, 10)",
                "DungeonFloorOverHeadLight1 (8, 1)",
                "DungeonFloorOverHeadLight1 (8, 2)",
                "DungeonFloorOverHeadLight1 (8, 3)",
                "DungeonFloorOverHeadLight1 (8, 4)",
                "DungeonFloorOverHeadLight1 (8, 5)",
                "DungeonFloorOverHeadLight1 (8, 6)",
                "DungeonFloorOverHeadLight1 (8, 7)",
                "DungeonFloorOverHeadLight1 (8, 8)",
                "DungeonFloorOverHeadLight1 (8, 9)",
                "DungeonFloorOverHeadLight1 (8, 10)",
                "DungeonFloorOverHeadLight1 (9, 1)",
                "DungeonFloorOverHeadLight1 (9, 2)",
                "DungeonFloorOverHeadLight1 (9, 3)",
                "DungeonFloorOverHeadLight1 (9, 4)",
                "DungeonFloorOverHeadLight1 (9, 5)",
                "DungeonFloorOverHeadLight1 (9, 6)",
                "DungeonFloorOverHeadLight1 (9, 7)",
                "DungeonFloorOverHeadLight1 (9, 8)",
                "DungeonFloorOverHeadLight1 (9, 9)",
                "DungeonFloorOverHeadLight1 (9, 10)",
                "DungeonFloorOverHeadLight1 (10, 1)",
                "DungeonFloorOverHeadLight1 (10, 2)",
                "DungeonFloorOverHeadLight1 (10, 3)",
                "DungeonFloorOverHeadLight1 (10, 4)",
                "DungeonFloorOverHeadLight1 (10, 5)",
                "DungeonFloorOverHeadLight1 (10, 6)",
                "DungeonFloorOverHeadLight1 (10, 7)",
                "DungeonFloorOverHeadLight1 (10, 8)",
                "DungeonFloorOverHeadLight1 (10, 9)",
                "DungeonFloorOverHeadLight1 (10, 10)")),
        new Definition(
            "0x2c",
            15,
            15,
            List.of(
                "DungeonFloorOverHead2 (8, 8)",
                "DungeonFloorOverHead2 (8, 9)",
                "DungeonFloorOverHead2 (8, 10)",
                "DungeonFloorOverHead2 (8, 11)",
                "DungeonFloorOverHead2 (8, 12)",
                "DungeonFloorOverHead2 (8, 13)",
                "DungeonFloorOverHead2 (8, 14)",
                "DungeonFloorOverHead2 (8, 15)",
                "DungeonFloorOverHead2 (8, 1)",
                "DungeonFloorOverHead2 (8, 2)",
                "DungeonFloorOverHead2 (8, 3)",
                "DungeonFloorOverHead2 (8, 4)",
                "DungeonFloorOverHead2 (8, 5)",
                "DungeonFloorOverHead2 (8, 6)",
                "DungeonFloorOverHead2 (8, 7)",
                "DungeonFloorOverHead2 (9, 8)",
                "DungeonFloorOverHead2 (9, 9)",
                "DungeonFloorOverHead2 (9, 10)",
                "DungeonFloorOverHead2 (9, 11)",
                "DungeonFloorOverHead2 (9, 12)",
                "DungeonFloorOverHead2 (9, 13)",
                "DungeonFloorOverHead2 (9, 14)",
                "DungeonFloorOverHead2 (9, 15)",
                "DungeonFloorOverHead2 (9, 1)",
                "DungeonFloorOverHead2 (9, 2)",
                "DungeonFloorOverHead2 (9, 3)",
                "DungeonFloorOverHead2 (9, 4)",
                "DungeonFloorOverHead2 (9, 5)",
                "DungeonFloorOverHead2 (9, 6)",
                "DungeonFloorOverHead2 (9, 7)",
                "DungeonFloorOverHead2 (10, 8)",
                "DungeonFloorOverHead2 (10, 9)",
                "DungeonFloorOverHead2 (10, 10)",
                "DungeonFloorOverHead2 (10, 11)",
                "DungeonFloorOverHead2 (10, 12)",
                "DungeonFloorOverHead2 (10, 13)",
                "DungeonFloorOverHead2 (10, 14)",
                "DungeonFloorOverHead2 (10, 15)",
                "DungeonFloorOverHead2 (10, 1)",
                "DungeonFloorOverHead2 (10, 2)",
                "DungeonFloorOverHead2 (10, 3)",
                "DungeonFloorOverHead2 (10, 4)",
                "DungeonFloorOverHead2 (10, 5)",
                "DungeonFloorOverHead2 (10, 6)",
                "DungeonFloorOverHead2 (10, 7)",
                "DungeonFloorOverHead2 (11, 8)",
                "DungeonFloorOverHead2 (11, 9)",
                "DungeonFloorOverHead2 (11, 10)",
                "DungeonFloorOverHead2 (11, 11)",
                "DungeonFloorOverHead2 (11, 12)",
                "DungeonFloorOverHead2 (11, 13)",
                "DungeonFloorOverHead2 (11, 14)",
                "DungeonFloorOverHead2 (11, 15)",
                "DungeonFloorOverHead2 (11, 1)",
                "DungeonFloorOverHead2 (11, 2)",
                "DungeonFloorOverHead2 (11, 3)",
                "DungeonFloorOverHead2 (11, 4)",
                "DungeonFloorOverHead2 (11, 5)",
                "DungeonFloorOverHead2 (11, 6)",
                "DungeonFloorOverHead2 (11, 7)",
                "DungeonFloorOverHead2 (12, 8)",
                "DungeonFloorOverHead2 (12, 9)",
                "DungeonFloorOverHead2 (12, 10)",
                "DungeonFloorOverHead2 (12, 11)",
                "DungeonFloorOverHead2 (12, 12)",
                "DungeonFloorOverHead2 (12, 13)",
                "DungeonFloorOverHead2 (12, 14)",
                "DungeonFloorOverHead2 (12, 15)",
                "DungeonFloorOverHead2 (12, 1)",
                "DungeonFloorOverHead2 (12, 2)",
                "DungeonFloorOverHead2 (12, 3)",
                "DungeonFloorOverHead2 (12, 4)",
                "DungeonFloorOverHead2 (12, 5)",
                "DungeonFloorOverHead2 (12, 6)",
                "DungeonFloorOverHead2 (12, 7)",
                "DungeonFloorOverHead2 (13, 8)",
                "DungeonFloorOverHead2 (13, 9)",
                "DungeonFloorOverHead2 (13, 10)",
                "DungeonFloorOverHead2 (13, 11)",
                "DungeonFloorOverHead2 (13, 12)",
                "DungeonFloorOverHead2 (13, 13)",
                "DungeonFloorOverHead2 (13, 14)",
                "DungeonFloorOverHead2 (13, 15)",
                "DungeonFloorOverHead2 (13, 1)",
                "DungeonFloorOverHead2 (13, 2)",
                "DungeonFloorOverHead2 (13, 3)",
                "DungeonFloorOverHead2 (13, 4)",
                "DungeonFloorOverHead2 (13, 5)",
                "DungeonFloorOverHead2 (13, 6)",
                "DungeonFloorOverHead2 (13, 7)",
                "DungeonFloorOverHead2 (14, 8)",
                "DungeonFloorOverHead2 (14, 9)",
                "DungeonFloorOverHead2 (14, 10)",
                "DungeonFloorOverHead2 (14, 11)",
                "DungeonFloorOverHead2 (14, 12)",
                "DungeonFloorOverHead2 (14, 13)",
                "DungeonFloorOverHead2 (14, 14)",
                "DungeonFloorOverHead2 (14, 15)",
                "DungeonFloorOverHead2 (14, 1)",
                "DungeonFloorOverHead2 (14, 2)",
                "DungeonFloorOverHead2 (14, 3)",
                "DungeonFloorOverHead2 (14, 4)",
                "DungeonFloorOverHead2 (14, 5)",
                "DungeonFloorOverHead2 (14, 6)",
                "DungeonFloorOverHead2 (14, 7)",
                "DungeonFloorOverHead2 (15, 8)",
                "DungeonFloorOverHead2 (15, 9)",
                "DungeonFloorOverHead2 (15, 10)",
                "DungeonFloorOverHead2 (15, 11)",
                "DungeonFloorOverHead2 (15, 12)",
                "DungeonFloorOverHead2 (15, 13)",
                "DungeonFloorOverHead2 (15, 14)",
                "DungeonFloorOverHead2 (15, 15)",
                "DungeonFloorOverHead2 (15, 1)",
                "DungeonFloorOverHead2 (15, 2)",
                "DungeonFloorOverHead2 (15, 3)",
                "DungeonFloorOverHead2 (15, 4)",
                "DungeonFloorOverHead2 (15, 5)",
                "DungeonFloorOverHead2 (15, 6)",
                "DungeonFloorOverHead2 (15, 7)",
                "DungeonFloorOverHead2 (1, 8)",
                "DungeonFloorOverHead2 (1, 9)",
                "DungeonFloorOverHead2 (1, 10)",
                "DungeonFloorOverHead2 (1, 11)",
                "DungeonFloorOverHead2 (1, 12)",
                "DungeonFloorOverHead2 (1, 13)",
                "DungeonFloorOverHead2 (1, 14)",
                "DungeonFloorOverHead2 (1, 15)",
                "DungeonFloorOverHead2 (1, 1)",
                "DungeonFloorOverHead2 (1, 2)",
                "DungeonFloorOverHead2 (1, 3)",
                "DungeonFloorOverHead2 (1, 4)",
                "DungeonFloorOverHead2 (1, 5)",
                "DungeonFloorOverHead2 (1, 6)",
                "DungeonFloorOverHead2 (1, 7)",
                "DungeonFloorOverHead2 (2, 8)",
                "DungeonFloorOverHead2 (2, 9)",
                "DungeonFloorOverHead2 (2, 10)",
                "DungeonFloorOverHead2 (2, 11)",
                "DungeonFloorOverHead2 (2, 12)",
                "DungeonFloorOverHead2 (2, 13)",
                "DungeonFloorOverHead2 (2, 14)",
                "DungeonFloorOverHead2 (2, 15)",
                "DungeonFloorOverHead2 (2, 1)",
                "DungeonFloorOverHead2 (2, 2)",
                "DungeonFloorOverHead2 (2, 3)",
                "DungeonFloorOverHead2 (2, 4)",
                "DungeonFloorOverHead2 (2, 5)",
                "DungeonFloorOverHead2 (2, 6)",
                "DungeonFloorOverHead2 (2, 7)",
                "DungeonFloorOverHead2 (3, 8)",
                "DungeonFloorOverHead2 (3, 9)",
                "DungeonFloorOverHead2 (3, 10)",
                "DungeonFloorOverHead2 (3, 11)",
                "DungeonFloorOverHead2 (3, 12)",
                "DungeonFloorOverHead2 (3, 13)",
                "DungeonFloorOverHead2 (3, 14)",
                "DungeonFloorOverHead2 (3, 15)",
                "DungeonFloorOverHead2 (3, 1)",
                "DungeonFloorOverHead2 (3, 2)",
                "DungeonFloorOverHead2 (3, 3)",
                "DungeonFloorOverHead2 (3, 4)",
                "DungeonFloorOverHead2 (3, 5)",
                "DungeonFloorOverHead2 (3, 6)",
                "DungeonFloorOverHead2 (3, 7)",
                "DungeonFloorOverHead2 (4, 8)",
                "DungeonFloorOverHead2 (4, 9)",
                "DungeonFloorOverHead2 (4, 10)",
                "DungeonFloorOverHead2 (4, 11)",
                "DungeonFloorOverHead2 (4, 12)",
                "DungeonFloorOverHead2 (4, 13)",
                "DungeonFloorOverHead2 (4, 14)",
                "DungeonFloorOverHead2 (4, 15)",
                "DungeonFloorOverHead2 (4, 1)",
                "DungeonFloorOverHead2 (4, 2)",
                "DungeonFloorOverHead2 (4, 3)",
                "DungeonFloorOverHead2 (4, 4)",
                "DungeonFloorOverHead2 (4, 5)",
                "DungeonFloorOverHead2 (4, 6)",
                "DungeonFloorOverHead2 (4, 7)",
                "DungeonFloorOverHead2 (5, 8)",
                "DungeonFloorOverHead2 (5, 9)",
                "DungeonFloorOverHead2 (5, 10)",
                "DungeonFloorOverHead2 (5, 11)",
                "DungeonFloorOverHead2 (5, 12)",
                "DungeonFloorOverHead2 (5, 13)",
                "DungeonFloorOverHead2 (5, 14)",
                "DungeonFloorOverHead2 (5, 15)",
                "DungeonFloorOverHead2 (5, 1)",
                "DungeonFloorOverHead2 (5, 2)",
                "DungeonFloorOverHead2 (5, 3)",
                "DungeonFloorOverHead2 (5, 4)",
                "DungeonFloorOverHead2 (5, 5)",
                "DungeonFloorOverHead2 (5, 6)",
                "DungeonFloorOverHead2 (5, 7)",
                "DungeonFloorOverHead2 (6, 8)",
                "DungeonFloorOverHead2 (6, 9)",
                "DungeonFloorOverHead2 (6, 10)",
                "DungeonFloorOverHead2 (6, 11)",
                "DungeonFloorOverHead2 (6, 12)",
                "DungeonFloorOverHead2 (6, 13)",
                "DungeonFloorOverHead2 (6, 14)",
                "DungeonFloorOverHead2 (6, 15)",
                "DungeonFloorOverHead2 (6, 1)",
                "DungeonFloorOverHead2 (6, 2)",
                "DungeonFloorOverHead2 (6, 3)",
                "DungeonFloorOverHead2 (6, 4)",
                "DungeonFloorOverHead2 (6, 5)",
                "DungeonFloorOverHead2 (6, 6)",
                "DungeonFloorOverHead2 (6, 7)",
                "DungeonFloorOverHead2 (7, 8)",
                "DungeonFloorOverHead2 (7, 9)",
                "DungeonFloorOverHead2 (7, 10)",
                "DungeonFloorOverHead2 (7, 11)",
                "DungeonFloorOverHead2 (7, 12)",
                "DungeonFloorOverHead2 (7, 13)",
                "DungeonFloorOverHead2 (7, 14)",
                "DungeonFloorOverHead2 (7, 15)",
                "DungeonFloorOverHead2 (7, 1)",
                "DungeonFloorOverHead2 (7, 2)",
                "DungeonFloorOverHead2 (7, 3)",
                "DungeonFloorOverHead2 (7, 4)",
                "DungeonFloorOverHead2 (7, 5)",
                "DungeonFloorOverHead2 (7, 6)",
                "DungeonFloorOverHead2 (7, 7)")),
        new Definition(
            "0x104",
            8,
            9,
            List.of(
                "64kNormalGrassBreaker1 (1, 1)",
                "64kNormalGrassBreaker1 (1, 2)",
                "64kNormalGrassBreaker1 (1, 3)",
                "64kNormalGrassBreaker1 (1, 4)",
                "64kNormalGrassBreaker1 (1, 5)",
                "64kNormalGrassBreaker1 (1, 6)",
                "64kNormalGrassBreaker1 (1, 7)",
                "64kNormalGrassBreaker1 (1, 8)",
                "64kNormalGrassBreaker1 (1, 9)",
                "64kNormalGrassBreaker1 (2, 1)",
                "64kNormalGrassBreaker1 (2, 2)",
                "64kNormalGrassBreaker1 (2, 3)",
                "64kNormalGrassBreaker1 (2, 4)",
                "64kNormalGrassBreaker1 (2, 5)",
                "64kNormalGrassBreaker1 (2, 6)",
                "64kNormalGrassBreaker1 (2, 7)",
                "64kNormalGrassBreaker1 (2, 8)",
                "64kNormalGrassBreaker1 (2, 9)",
                "64kNormalGrassBreaker1 (3, 1)",
                "64kNormalGrassBreaker1 (3, 2)",
                "64kNormalGrassBreaker1 (3, 3)",
                "64kNormalGrassBreaker1 (3, 4)",
                "64kNormalGrassBreaker1 (3, 5)",
                "64kNormalGrassBreaker1 (3, 6)",
                "64kNormalGrassBreaker1 (3, 7)",
                "64kNormalGrassBreaker1 (3, 8)",
                "64kNormalGrassBreaker1 (3, 9)",
                "64kNormalGrassBreaker1 (4, 1)",
                "64kNormalGrassBreaker1 (4, 2)",
                "64kNormalGrassBreaker1 (4, 3)",
                "64kNormalGrassBreaker1 (4, 4)",
                "64kNormalGrassBreaker1 (4, 5)",
                "64kNormalGrassBreaker1 (4, 6)",
                "64kNormalGrassBreaker1 (4, 7)",
                "64kNormalGrassBreaker1 (4, 8)",
                "64kNormalGrassBreaker1 (4, 9)",
                "64kNormalGrassBreaker1 (5, 1)",
                "64kNormalGrassBreaker1 (5, 2)",
                "64kNormalGrassBreaker1 (5, 3)",
                "64kNormalGrassBreaker1 (5, 4)",
                "64kNormalGrassBreaker1 (5, 5)",
                "64kNormalGrassBreaker1 (5, 6)",
                "64kNormalGrassBreaker1 (5, 7)",
                "64kNormalGrassBreaker1 (5, 8)",
                "64kNormalGrassBreaker1 (5, 9)",
                "64kNormalGrassBreaker1 (6, 1)",
                "64kNormalGrassBreaker1 (6, 2)",
                "64kNormalGrassBreaker1 (6, 3)",
                "64kNormalGrassBreaker1 (6, 4)",
                "64kNormalGrassBreaker1 (6, 5)",
                "64kNormalGrassBreaker1 (6, 6)",
                "64kNormalGrassBreaker1 (6, 7)",
                "64kNormalGrassBreaker1 (6, 8)",
                "64kNormalGrassBreaker1 (6, 9)",
                "64kNormalGrassBreaker1 (7, 1)",
                "64kNormalGrassBreaker1 (7, 2)",
                "64kNormalGrassBreaker1 (7, 3)",
                "64kNormalGrassBreaker1 (7, 4)",
                "64kNormalGrassBreaker1 (7, 5)",
                "64kNormalGrassBreaker1 (7, 6)",
                "64kNormalGrassBreaker1 (7, 7)",
                "64kNormalGrassBreaker1 (7, 8)",
                "64kNormalGrassBreaker1 (7, 9)",
                "64kNormalGrassBreaker1 (8, 1)",
                "64kNormalGrassBreaker1 (8, 2)",
                "64kNormalGrassBreaker1 (8, 3)",
                "64kNormalGrassBreaker1 (8, 4)",
                "64kNormalGrassBreaker1 (8, 5)",
                "64kNormalGrassBreaker1 (8, 6)",
                "64kNormalGrassBreaker1 (8, 7)",
                "64kNormalGrassBreaker1 (8, 8)",
                "64kNormalGrassBreaker1 (8, 9)")),
        new Definition(
            "0x105",
            5,
            7,
            List.of(
                "64kNormalGrassBreaker2 (1, 1)",
                "64kNormalGrassBreaker2 (1, 2)",
                "64kNormalGrassBreaker2 (1, 3)",
                "64kNormalGrassBreaker2 (1, 4)",
                "64kNormalGrassBreaker2 (1, 5)",
                "64kNormalGrassBreaker2 (1, 6)",
                "64kNormalGrassBreaker2 (1, 7)",
                "64kNormalGrassBreaker2 (2, 1)",
                "64kNormalGrassBreaker2 (2, 2)",
                "64kNormalGrassBreaker2 (2, 3)",
                "64kNormalGrassBreaker2 (2, 4)",
                "64kNormalGrassBreaker2 (2, 5)",
                "64kNormalGrassBreaker2 (2, 6)",
                "64kNormalGrassBreaker2 (2, 7)",
                "64kNormalGrassBreaker2 (3, 1)",
                "64kNormalGrassBreaker2 (3, 2)",
                "64kNormalGrassBreaker2 (3, 3)",
                "64kNormalGrassBreaker2 (3, 4)",
                "64kNormalGrassBreaker2 (3, 5)",
                "64kNormalGrassBreaker2 (3, 6)",
                "64kNormalGrassBreaker2 (3, 7)",
                "64kNormalGrassBreaker2 (4, 1)",
                "64kNormalGrassBreaker2 (4, 2)",
                "64kNormalGrassBreaker2 (4, 3)",
                "64kNormalGrassBreaker2 (4, 4)",
                "64kNormalGrassBreaker2 (4, 5)",
                "64kNormalGrassBreaker2 (4, 6)",
                "64kNormalGrassBreaker2 (4, 7)",
                "64kNormalGrassBreaker2 (5, 1)",
                "64kNormalGrassBreaker2 (5, 2)",
                "64kNormalGrassBreaker2 (5, 3)",
                "64kNormalGrassBreaker2 (5, 4)",
                "64kNormalGrassBreaker2 (5, 5)",
                "64kNormalGrassBreaker2 (5, 6)",
                "64kNormalGrassBreaker2 (5, 7)")),
        new Definition("0x4ec", 2, 1, List.of("Blood1", "Blood2")),
        new Definition("0x4ed", 2, 1, List.of("SkeletonCorpse2", "SkeletonCorpsePile1")),
        new Definition("0x4ee", 2, 1, List.of("Head", "Heads")),
        new Definition("0x4f1", 3, 1, List.of("Painting1", "Painting2", "Painting3")),
        new Definition("0x4f2", 3, 1, List.of("Painting1", "Painting2", "Painting3")),
        new Definition(
            "0x516", 3, 1, List.of("Grande Table Rectangle Bois", "LongTable2", "Table2")),
        new Definition(
            "0x579", 3, 1, List.of("Grande Table Rectangle Bois", "LongTable2", "Table2")),
        new Definition(
            "0x9c5",
            5,
            1,
            List.of(
                "64kDungeonRockWall 3 MA",
                "64kDungeonRockWall 4 MA",
                "64kDungeonRockWall 5 MA",
                "64kDungeonRockWall 1 MA",
                "64kDungeonRockWall 2 MA")),
        new Definition(
            "0x9c6",
            5,
            1,
            List.of(
                "64kDungeonDarkRockWall 2 MA",
                "64kDungeonDarkRockWall 3 MA",
                "64kDungeonDarkRockWall 4 MA",
                "64kDungeonDarkRockWall 5 MA",
                "64kDungeonDarkRockWall 1 MA")),
        new Definition(
            "0x9e9",
            5,
            1,
            List.of(
                "64kDungeonRockArc 3 MA",
                "64kDungeonRockArc 4 MA",
                "64kDungeonRockArc 5 MA",
                "64kDungeonRockArc 1 MA",
                "64kDungeonRockArc 2 MA")),
        new Definition(
            "0x9ea",
            5,
            1,
            List.of(
                "64kDungeonRockArcDark 3 MA",
                "64kDungeonRockArcDark 4 MA",
                "64kDungeonRockArcDark 5 MA",
                "64kDungeonRockArcDark 1 MA",
                "64kDungeonRockArcDark 2 MA")),
        new Definition(
            "0xa15",
            5,
            1,
            List.of(
                "64kDungeonRockWall 1 GR",
                "64kDungeonRockWall 2 GR",
                "64kDungeonRockWall 3 GR",
                "64kDungeonRockWall 4 GR",
                "64kDungeonRockWall 5 GR")),
        new Definition(
            "0xa16",
            5,
            1,
            List.of(
                "64kDungeonDarkRockWall 1 GR",
                "64kDungeonDarkRockWall 2 GR",
                "64kDungeonDarkRockWall 3 GR",
                "64kDungeonDarkRockWall 4 GR",
                "64kDungeonDarkRockWall 5 GR")),
        new Definition(
            "0xa39",
            5,
            1,
            List.of(
                "64kDungeonRockArc 5 GR",
                "64kDungeonRockArc 1 GR",
                "64kDungeonRockArc 2 GR",
                "64kDungeonRockArc 3 GR",
                "64kDungeonRockArc 4 GR")),
        new Definition(
            "0xa3a",
            5,
            1,
            List.of(
                "64kDungeonRockArcDark 1 GR",
                "64kDungeonRockArcDark 2 GR",
                "64kDungeonRockArcDark 3 GR",
                "64kDungeonRockArcDark 4 GR",
                "64kDungeonRockArcDark 5 GR")),
        new Definition(
            "0xbcd", 4, 1, List.of("Tomb Carrer", "Tomb Hemisphere", "Tomb Croix", "Tomb Plaque")),
        new Definition(
            "0xbce", 4, 1, List.of("Tomb Carrer", "Tomb Hemisphere", "Tomb Croix", "Tomb Plaque")),
        new Definition(
            "0xbed", 3, 1, List.of("StuccoDarkWindowA", "StuccoDarkWindowB", "StuccoDarkWindowC")),
        new Definition(
            "0xbee", 3, 1, List.of("StuccoMainWindowC", "StuccoMainWindowB", "StuccoMainWindowA")),
        new Definition(
            "0xc38",
            3,
            1,
            List.of("64kDeadForestTree2", "64kDeadForestTree3", "64kDeadForestTree4")),
        new Definition(
            "0xc60", 4, 1, List.of("SmallTree4", "SmallTree3", "SmallTree2", "SmallTree1")),
        new Definition("0xc62", 2, 1, List.of("LeafLessTree2", "LeafLessTree1")),
        new Definition("0xc63", 3, 1, List.of("OakTree2", "OakTree1", "LargeBasedLowLeafedTree1")),
        new Definition("0xc64", 2, 1, List.of("NearlyLeafLessTree1", "MultiTrunkTree2")),
        new Definition("0xc65", 2, 1, List.of("PalmTree2", "PalmTree1")),
        new Definition("0xc66", 2, 1, List.of("LargePine1", "HighPine1")),
        new Definition("0xc67", 2, 1, List.of("CityTree2", "CityTree1")),
        new Definition("0xc69", 3, 1, List.of("LeafLessTree2", "LeafLessTree1", "DeadTree1")),
        new Definition("0xc6b", 3, 1, List.of("MultiTrunkTree1", "Bush2", "Bush1")),
        new Definition(
            "0xc6c", 4, 1, List.of("Fougere1", "Fougere2", "PlantModel1", "SmallRockPack1")),
        new Definition("0xc6d", 4, 1, List.of("Cactus1", "Cactus2", "HighCactus1", "HighCactus2")),
        new Definition(
            "0xc6f",
            6,
            1,
            List.of("DarkTree1", "DarkTree2", "DarkTree3", "DarkTree4", "DarkTree5", "DarkTree6")),
        new Definition("0xc74", 3, 1, List.of("FenceDark 2", "FenceDark 3", "FenceDark 1")),
        new Definition("0xc75", 3, 1, List.of("Fence 2", "Fence 3", "Fence 1")),
        new Definition("0xc96", 2, 1, List.of("Dummy", "Dummy2")),
        new Definition("0xc9c", 2, 1, List.of("AxeCross", "Sword")),
        new Definition("0xc9d", 2, 1, List.of("AxeCross", "Sword")),
        new Definition("0xca0", 2, 1, List.of("Dummy", "Dummy2")),
        new Definition(
            "0xcdc", 3, 1, List.of("BrickDarkWall 1", "BrickDarkWall 2", "BrickDarkWall 3")),
        new Definition("0xcdd", 3, 1, List.of("BrickWall 1", "BrickWall 2", "BrickWall 3")),
        new Definition(
            "0xcff",
            3,
            1,
            List.of("Ruined_BrickDarkWall 1", "Ruined_BrickDarkWall 2", "Ruined_BrickDarkWall 3")),
        new Definition(
            "0xd00",
            3,
            1,
            List.of("Ruined_BrickWall 1", "Ruined_BrickWall 2", "Ruined_BrickWall 3")),
        new Definition(
            "0xd01",
            3,
            1,
            List.of(
                "Ruined_BrickDarkWallWindow 1",
                "Ruined_BrickDarkWallWindow 2",
                "Ruined_BrickDarkWallWindow 3")),
        new Definition(
            "0xd02",
            3,
            1,
            List.of(
                "Ruined_BrickWallWindow 1",
                "Ruined_BrickWallWindow 2",
                "Ruined_BrickWallWindow 3")),
        new Definition("0xd1c", 4, 1, List.of("Rampart 5", "Rampart 2", "Rampart 3", "Rampart 4")),
        new Definition("0xd1e", 4, 1, List.of("Rampart 2", "Rampart 5", "Rampart 4", "Rampart 3")),
        new Definition(
            "0xd25",
            5,
            1,
            List.of(
                "DungeonDarkWall 1",
                "DungeonDarkWall 2",
                "DungeonDarkWall 3",
                "DungeonDarkWall 4",
                "DungeonDarkWall 5")),
        new Definition(
            "0xd26",
            5,
            1,
            List.of(
                "DungeonMainWall 1",
                "DungeonMainWall 2",
                "DungeonMainWall 3",
                "DungeonMainWall 4",
                "DungeonMainWall 5")),
        new Definition(
            "0xd49",
            5,
            1,
            List.of(
                "DungeonDarkTorch1 2",
                "DungeonDarkTorch1 3",
                "DungeonDarkTorch1 4",
                "DungeonDarkTorch1 5",
                "DungeonDarkTorch1 1")),
        new Definition(
            "0xd4a",
            5,
            1,
            List.of(
                "DungeonMainTorch1 2",
                "DungeonMainTorch1 3",
                "DungeonMainTorch1 4",
                "DungeonMainTorch1 5",
                "DungeonMainTorch1 1")),
        new Definition(
            "0xd53",
            5,
            1,
            List.of(
                "DungeonDarkArc 1",
                "DungeonDarkArc 2",
                "DungeonDarkArc 3",
                "DungeonDarkArc 4",
                "DungeonDarkArc 5")),
        new Definition(
            "0xd54",
            5,
            1,
            List.of(
                "DungeonMainArc 1",
                "DungeonMainArc 2",
                "DungeonMainArc 3",
                "DungeonMainArc 4",
                "DungeonMainArc 5")),
        new Definition(
            "0xd70", 3, 1, List.of("BrickDarkWall 1", "BrickDarkWall 2", "BrickDarkWall 3")),
        new Definition("0xd71", 3, 1, List.of("BrickWall 1", "BrickWall 2", "BrickWall 3")),
        new Definition("0xdb3", 3, 1, List.of("Trunk1", "Trunk2", "Trunk3")),
        new Definition(
            "0xdc9",
            9,
            1,
            List.of(
                "CavernTopWall 9",
                "CavernTopWall 1",
                "CavernTopWall 2",
                "CavernTopWall 3",
                "CavernTopWall 4",
                "CavernTopWall 5",
                "CavernTopWall 6",
                "CavernTopWall 7",
                "CavernTopWall 8")),
        new Definition(
            "0xdca",
            9,
            1,
            List.of(
                "CavernWall 5",
                "CavernWall 6",
                "CavernWall 7",
                "CavernWall 8",
                "CavernWall 9",
                "CavernWall 1",
                "CavernWall 2",
                "CavernWall 3",
                "CavernWall 4")),
        new Definition(
            "0xde6",
            9,
            1,
            List.of(
                "CavernLowWall 4",
                "CavernLowWall 5",
                "CavernLowWall 6",
                "CavernLowWall 7",
                "CavernLowWall 8",
                "CavernLowWall 9",
                "CavernLowWall 1",
                "CavernLowWall 2",
                "CavernLowWall 3")),
        new Definition(
            "0xde7",
            9,
            1,
            List.of(
                "CavernRightWall 4",
                "CavernRightWall 5",
                "CavernRightWall 6",
                "CavernRightWall 7",
                "CavernRightWall 8",
                "CavernRightWall 9",
                "CavernRightWall 1",
                "CavernRightWall 2",
                "CavernRightWall 3")),
        new Definition(
            "0xe09",
            5,
            1,
            List.of(
                "64kDungeonRockWall 3 BR",
                "64kDungeonRockWall 4 BR",
                "64kDungeonRockWall 5 BR",
                "64kDungeonRockWall 1 BR",
                "64kDungeonRockWall 2 BR")),
        new Definition(
            "0xe0a",
            5,
            1,
            List.of(
                "64kDungeonDarkRockWall 2 BR",
                "64kDungeonDarkRockWall 3 BR",
                "64kDungeonDarkRockWall 4 BR",
                "64kDungeonDarkRockWall 5 BR",
                "64kDungeonDarkRockWall 1 BR")),
        new Definition(
            "0xe2e",
            5,
            1,
            List.of(
                "64kDungeonRockArc 3 BR",
                "64kDungeonRockArc 4 BR",
                "64kDungeonRockArc 5 BR",
                "64kDungeonRockArc 1 BR",
                "64kDungeonRockArc 2 BR")),
        new Definition(
            "0xe2f",
            5,
            1,
            List.of(
                "64kDungeonRockArcDark 2 BR",
                "64kDungeonRockArcDark 3 BR",
                "64kDungeonRockArcDark 4 BR",
                "64kDungeonRockArcDark 5 BR",
                "64kDungeonRockArcDark 1 BR")),
        new Definition(
            "0xe5a",
            5,
            1,
            List.of(
                "CastleWall 1", "CastleWall 2", "CastleWall 3", "CastleWall 4", "CastleWall 5")),
        new Definition(
            "0xe5b",
            5,
            1,
            List.of(
                "CastleDarkWall 1",
                "CastleDarkWall 2",
                "CastleDarkWall 3",
                "CastleDarkWall 4",
                "CastleDarkWall 5")),
        new Definition(
            "0xed0",
            3,
            1,
            List.of(
                "Ruined_StuccoDarkWall 1", "Ruined_StuccoDarkWall 2", "Ruined_StuccoDarkWall 3")),
        new Definition(
            "0xed1",
            3,
            1,
            List.of(
                "Ruined_StuccoMainWall 1", "Ruined_StuccoMainWall 2", "Ruined_StuccoMainWall 3")),
        new Definition(
            "0xed2",
            3,
            1,
            List.of(
                "Ruined_StuccoDarkWindow 1",
                "Ruined_StuccoDarkWindow 2",
                "Ruined_StuccoDarkWindow 3")),
        new Definition(
            "0xed3",
            3,
            1,
            List.of(
                "Ruined_StuccoMainWindow 1",
                "Ruined_StuccoMainWindow 2",
                "Ruined_StuccoMainWindow 3")),
        new Definition(
            "0xf0e",
            5,
            1,
            List.of(
                "64kDungeonRockWall 3 BL",
                "64kDungeonRockWall 4 BL",
                "64kDungeonRockWall 5 BL",
                "64kDungeonRockWall 1 BL",
                "64kDungeonRockWall 2 BL")),
        new Definition(
            "0xf0f",
            5,
            1,
            List.of(
                "64kDungeonDarkRockWall 2 BL",
                "64kDungeonDarkRockWall 3 BL",
                "64kDungeonDarkRockWall 4 BL",
                "64kDungeonDarkRockWall 5 BL",
                "64kDungeonDarkRockWall 1 BL")),
        new Definition(
            "0xf32",
            5,
            1,
            List.of(
                "64kDungeonRockArc 3 BL",
                "64kDungeonRockArc 4 BL",
                "64kDungeonRockArc 5 BL",
                "64kDungeonRockArc 1 BL",
                "64kDungeonRockArc 2 BL")),
        new Definition("0x2", 11, 10, List.of("EarthTile (&x, &y)")));
  }
}
