package com.perso.T4C.monster;

import java.util.Map;
import com.perso.T4C.exception.GameException;
import com.perso.T4C.monster.core.DataMonster;
import com.perso.T4C.monster.core.MonsterDef;
import com.perso.T4C.spawn.Spawn;

@Spawn(type = "Brown Rat", x = 1001, y = 142, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1007, y = 1028, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1025, y = 2877, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1029, y = 190, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1040, y = 181, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1060, y = 2124, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1061, y = 2021, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1071, y = 272, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1076, y = 280, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1079, y = 2280, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1098, y = 1942, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 111, y = 2723, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 111, y = 650, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 112, y = 2241, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1130, y = 2330, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1135, y = 2243, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 114, y = 2078, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 114, y = 402, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1140, y = 2073, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 115, y = 549, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1157, y = 2217, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 118, y = 551, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1181, y = 2073, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1187, y = 2396, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1189, y = 2502, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 119, y = 688, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1199, y = 2436, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1199, y = 2504, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1219, y = 2027, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 122, y = 2951, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1221, y = 2331, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 125, y = 2160, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1250, y = 1936, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1266, y = 2006, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 127, y = 297, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1271, y = 2166, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 129, y = 2582, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 129, y = 2869, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 130, y = 494, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 131, y = 2674, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 131, y = 494, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 1314, y = 1987, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 136, y = 2399, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 137, y = 2293, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 138, y = 1052, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 140, y = 374, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 140, y = 853, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 141, y = 961, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 144, y = 3002, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 145, y = 2066, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 146, y = 1037, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 146, y = 274, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 150, y = 520, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 153, y = 2482, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 154, y = 885, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 155, y = 949, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 16, y = 475, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 161, y = 2221, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 162, y = 2744, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 164, y = 431, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 166, y = 2842, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 166, y = 366, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 168, y = 2859, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 169, y = 193, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 171, y = 610, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 172, y = 2163, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 172, y = 524, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 173, y = 2887, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 176, y = 2031, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 176, y = 472, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 178, y = 517, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 18, y = 296, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 181, y = 475, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 187, y = 173, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 188, y = 2008, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 189, y = 200, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 190, y = 886, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 192, y = 627, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 194, y = 195, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 197, y = 105, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 197, y = 704, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 198, y = 889, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 200, y = 80, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 201, y = 510, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 202, y = 2126, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 203, y = 2889, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 209, y = 151, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 209, y = 2366, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 210, y = 431, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 211, y = 2041, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 215, y = 928, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 217, y = 3005, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 218, y = 2173, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 218, y = 685, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 218, y = 836, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 219, y = 853, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 220, y = 474, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 222, y = 472, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 222, y = 517, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 222, y = 660, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 224, y = 1084, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 224, y = 2571, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 225, y = 521, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 226, y = 2958, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 231, y = 161, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 233, y = 77, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 234, y = 154, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 234, y = 979, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 235, y = 852, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 236, y = 2877, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 236, y = 728, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 239, y = 181, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 240, y = 47, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 243, y = 2079, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 244, y = 1098, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 244, y = 2244, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 244, y = 408, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 245, y = 65, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 246, y = 2807, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 247, y = 2923, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 248, y = 116, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 248, y = 522, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 250, y = 518, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 252, y = 463, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 255, y = 2680, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 259, y = 2943, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 261, y = 2298, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 261, y = 446, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 2655, y = 395, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 2662, y = 394, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 2683, y = 372, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 270, y = 2102, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 270, y = 492, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 271, y = 885, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 2726, y = 379, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 276, y = 149, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 276, y = 2344, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 278, y = 1189, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 278, y = 605, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 278, y = 735, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 284, y = 342, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 288, y = 2743, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 289, y = 1160, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 291, y = 2801, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 291, y = 62, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 292, y = 385, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 292, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 294, y = 296, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 294, y = 85, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 296, y = 105, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 297, y = 2358, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 303, y = 732, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 306, y = 2300, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 306, y = 403, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 309, y = 1087, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 310, y = 1020, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 313, y = 2519, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 315, y = 274, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 321, y = 654, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 326, y = 684, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 328, y = 384, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 329, y = 882, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 33, y = 195, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 330, y = 332, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 331, y = 1078, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 332, y = 2276, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 334, y = 402, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 334, y = 510, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 334, y = 944, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 339, y = 372, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 342, y = 2118, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 348, y = 82, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 350, y = 2555, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 353, y = 335, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 354, y = 326, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 357, y = 2334, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 360, y = 408, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 362, y = 286, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 365, y = 2629, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 365, y = 85, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 368, y = 411, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 371, y = 1058, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 372, y = 547, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 372, y = 854, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 376, y = 230, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 376, y = 888, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 377, y = 377, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 380, y = 101, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 386, y = 804, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 387, y = 386, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 390, y = 620, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 393, y = 449, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 405, y = 300, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 408, y = 324, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 41, y = 484, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 410, y = 441, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 411, y = 2121, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 413, y = 622, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 415, y = 2266, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 417, y = 376, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 418, y = 884, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 42, y = 324, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 421, y = 1051, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 421, y = 414, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 424, y = 2486, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 427, y = 875, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 429, y = 1024, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 429, y = 2637, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 430, y = 583, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 434, y = 890, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 436, y = 2214, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 437, y = 539, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 439, y = 2605, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 44, y = 1788, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 441, y = 269, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 441, y = 757, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 441, y = 863, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 444, y = 788, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 445, y = 956, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 446, y = 279, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 447, y = 228, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 449, y = 328, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 453, y = 241, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 454, y = 145, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 455, y = 316, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 459, y = 2587, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 459, y = 938, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 46, y = 1785, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 461, y = 1046, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 463, y = 557, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 47, y = 180, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 475, y = 265, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 477, y = 2605, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 48, y = 1786, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 482, y = 820, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 482, y = 973, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 486, y = 427, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 492, y = 999, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 494, y = 752, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 496, y = 324, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 503, y = 615, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 504, y = 1040, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 504, y = 839, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 506, y = 2142, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 510, y = 792, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 513, y = 751, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 514, y = 862, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 514, y = 891, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 514, y = 940, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 520, y = 675, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 521, y = 555, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 522, y = 390, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 527, y = 918, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 53, y = 1795, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 530, y = 1007, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 533, y = 759, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 535, y = 482, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 536, y = 585, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 545, y = 541, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 549, y = 2916, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 55, y = 263, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 553, y = 262, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 555, y = 670, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 556, y = 915, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 558, y = 947, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 566, y = 547, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 581, y = 2987, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 581, y = 675, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 584, y = 2812, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 586, y = 755, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 593, y = 2743, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 593, y = 699, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 594, y = 492, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 595, y = 885, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 60, y = 356, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 605, y = 2780, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 61, y = 491, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 616, y = 484, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 616, y = 523, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 618, y = 2255, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 638, y = 2910, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 647, y = 881, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 65, y = 371, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 651, y = 2817, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 654, y = 2521, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 655, y = 785, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 66, y = 634, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 668, y = 834, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 672, y = 2177, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 676, y = 2074, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 682, y = 2141, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 682, y = 2602, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 685, y = 2874, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 69, y = 1763, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 701, y = 560, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 718, y = 585, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 719, y = 197, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 72, y = 1761, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 731, y = 2977, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 735, y = 183, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 739, y = 2470, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 75, y = 1765, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 751, y = 607, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 752, y = 2625, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 758, y = 2832, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 759, y = 2182, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 772, y = 575, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 778, y = 2308, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 779, y = 1957, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 780, y = 583, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 784, y = 578, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 793, y = 571, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 794, y = 641, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 797, y = 2597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 797, y = 525, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 797, y = 635, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 797, y = 639, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 806, y = 2476, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 807, y = 2476, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 812, y = 606, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 814, y = 2603, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 816, y = 170, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 819, y = 517, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 824, y = 2317, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 827, y = 514, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 83, y = 211, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 837, y = 2540, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 838, y = 2468, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 839, y = 497, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 841, y = 156, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 847, y = 582, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 848, y = 775, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 849, y = 775, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 85, y = 291, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 859, y = 1008, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 861, y = 582, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 863, y = 2042, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 866, y = 2058, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 871, y = 2841, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 881, y = 2668, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 886, y = 2249, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 903, y = 2748, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 908, y = 2178, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 91, y = 643, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 92, y = 377, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 94, y = 621, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 941, y = 685, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 945, y = 689, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 98, y = 223, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 993, y = 202, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 995, y = 210, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Brown Rat", x = 998, y = 1041, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Rat", x = 291, y = 390, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Rat", x = 304, y = 375, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Rat", x = 306, y = 408, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Rat", x = 317, y = 416, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Rat", x = 325, y = 402, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Rat", x = 328, y = 383, z = 1, stationary = false, aggressive = true)
public final class BrownRat extends DataMonster {
  public static final String SOUND_ATTACK = "Rat Attack.wav";
  public static final String SOUND_DEATH = "Rat Dying.wav";
  public static final String SOUND_HIT = "Rat Hit.wav";

  public static final String CANONICAL_NAME = "Brown Rat";

  public BrownRat(MonsterDef definition, float x, float y) throws GameException {

    super(definition, x, y);
  }

  @Override
  public String getCanonicalName() {

    return CANONICAL_NAME;
  }

  public static MonsterDef definition() {
    return new MonsterDef(
        "Brown Rat",
        "${monster.brown_rat}",
        27,
        0,
        1,
        21,
        2,
        5,
        30000L,
        "Rat#f",
        "RatA#i",
        "RatC!j",
        SOUND_ATTACK,
        SOUND_DEATH,
        SOUND_HIT,
        1,
        5,
        java.util.List.of(new MonsterDef.LootDrop("Torch", 0.02f)),
        false,
        0.0f,
        16,
        15,
        15,
        16,
        0,
        15,
        0,
        new int[] {124, 62, 93, 93, 93, 5000, 100, 100, 100, 100, 100, 100},
        1,
        14,
        0,
        0,
        20003,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        50,
        16,
        0,
        true,
        java.util.List.of(new MonsterDef.Attack("1d4+1", 22, 100, 0, 0, 0)),
        true,
        10,
        java.util.List.of("Rat"),
        java.util.Map.of());
  }
}
