package com.perso.T4C.monster;

import java.util.Map;
import com.perso.T4C.exception.GameException;
import com.perso.T4C.monster.core.DataMonster;
import com.perso.T4C.monster.core.MonsterDef;
import com.perso.T4C.spawn.Spawn;

@Spawn(type = "Goblin Scout", x = 1033, y = 2206, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1034, y = 2203, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1052, y = 2224, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1054, y = 2131, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1056, y = 2026, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1056, y = 2221, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1056, y = 2223, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1058, y = 2055, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1058, y = 2074, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1067, y = 244, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1086, y = 264, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1089, y = 1950, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1092, y = 2252, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1099, y = 2053, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1102, y = 2312, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1104, y = 2020, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1104, y = 2175, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1104, y = 250, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1105, y = 2018, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1105, y = 259, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1106, y = 1945, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1106, y = 2127, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1107, y = 2017, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1117, y = 2294, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1118, y = 2070, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1118, y = 2345, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 112, y = 2732, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1129, y = 2114, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 113, y = 2518, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1135, y = 2068, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1146, y = 2079, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1170, y = 2251, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1172, y = 2240, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1181, y = 2103, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1182, y = 2114, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1183, y = 2091, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1186, y = 2038, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 119, y = 2554, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1192, y = 2035, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1193, y = 2295, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1200, y = 2286, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1206, y = 2030, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1229, y = 2093, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1233, y = 2022, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1237, y = 2025, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1240, y = 2059, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1240, y = 2070, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1242, y = 2089, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1245, y = 1962, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1253, y = 2002, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1253, y = 2069, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1254, y = 2003, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1255, y = 2004, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1259, y = 1938, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1270, y = 1977, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1273, y = 1952, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1277, y = 1989, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1279, y = 1950, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1292, y = 2016, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1300, y = 2007, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 131, y = 2509, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1320, y = 2008, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 137, y = 2695, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 147, y = 2934, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 149, y = 2486, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 152, y = 2885, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 158, y = 2952, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 159, y = 2888, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 160, y = 2738, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 161, y = 2563, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 161, y = 2885, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1689, y = 347, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1691, y = 381, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1691, y = 411, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1713, y = 223, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1713, y = 434, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 172, y = 2703, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1730, y = 443, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1730, y = 462, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 175, y = 3002, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1750, y = 180, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1755, y = 453, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1763, y = 164, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1766, y = 1381, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1772, y = 170, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1778, y = 238, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1780, y = 528, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1781, y = 441, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1785, y = 515, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1786, y = 218, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1789, y = 522, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1790, y = 543, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1795, y = 303, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1796, y = 435, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1798, y = 326, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1807, y = 203, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1812, y = 177, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1813, y = 370, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1813, y = 526, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1819, y = 156, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1822, y = 1339, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1824, y = 194, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1829, y = 417, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1831, y = 569, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1832, y = 147, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1836, y = 343, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1839, y = 1314, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 184, y = 2685, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1845, y = 354, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1849, y = 150, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1849, y = 212, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1849, y = 567, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1852, y = 337, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1855, y = 206, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1856, y = 422, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1857, y = 400, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 186, y = 2691, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1863, y = 564, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1871, y = 542, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1876, y = 401, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1877, y = 428, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1883, y = 1012, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1886, y = 570, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1888, y = 588, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1890, y = 170, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1893, y = 547, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1899, y = 1010, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1909, y = 596, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 191, y = 2644, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1917, y = 205, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1922, y = 135, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1923, y = 212, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1927, y = 588, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1928, y = 441, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 193, y = 2932, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1936, y = 548, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1939, y = 337, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1949, y = 124, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1951, y = 539, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1953, y = 352, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1958, y = 456, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1960, y = 1038, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1961, y = 1032, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1961, y = 534, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1968, y = 354, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1975, y = 239, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1979, y = 277, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 198, y = 2784, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1980, y = 533, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1981, y = 296, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1986, y = 317, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1988, y = 265, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1995, y = 1208, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1996, y = 428, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 1998, y = 361, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2005, y = 490, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2006, y = 503, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2007, y = 1126, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2010, y = 127, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2013, y = 511, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2016, y = 1188, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2017, y = 455, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 202, y = 2649, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2020, y = 1151, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2025, y = 1121, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2028, y = 1061, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2028, y = 481, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2031, y = 1072, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2035, y = 243, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2038, y = 1188, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2043, y = 1065, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2044, y = 133, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2049, y = 273, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2057, y = 1039, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2066, y = 497, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2076, y = 1057, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2085, y = 1046, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2087, y = 118, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 210, y = 2478, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2101, y = 446, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2102, y = 132, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 211, y = 2671, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2112, y = 457, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2117, y = 116, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2125, y = 406, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2131, y = 425, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2136, y = 1075, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2137, y = 1006, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2137, y = 1019, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2140, y = 126, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2141, y = 324, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 215, y = 2656, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2150, y = 206, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2152, y = 133, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2152, y = 408, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2154, y = 285, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2156, y = 317, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2157, y = 257, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2164, y = 1093, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2168, y = 238, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2169, y = 181, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 217, y = 2876, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2170, y = 257, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2175, y = 344, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2175, y = 345, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2176, y = 249, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2176, y = 945, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2177, y = 1089, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2181, y = 263, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2182, y = 136, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2187, y = 438, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2189, y = 1147, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 219, y = 2763, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2190, y = 455, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2191, y = 135, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2195, y = 979, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2203, y = 925, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2205, y = 1137, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2209, y = 991, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2210, y = 274, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2214, y = 915, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2215, y = 1159, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2217, y = 1335, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2218, y = 288, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2222, y = 439, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2223, y = 1176, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2223, y = 384, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2225, y = 1005, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2227, y = 1111, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2229, y = 198, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2229, y = 906, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2233, y = 218, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2234, y = 1363, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2239, y = 1020, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2242, y = 1182, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2244, y = 1084, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2244, y = 352, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2244, y = 447, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2245, y = 349, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2248, y = 1075, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2251, y = 1057, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2251, y = 248, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2251, y = 373, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2252, y = 1207, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2255, y = 901, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2259, y = 1348, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2266, y = 216, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2266, y = 392, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2271, y = 1219, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2272, y = 491, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2276, y = 1379, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2276, y = 423, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2276, y = 443, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2277, y = 271, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2279, y = 1307, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2281, y = 131, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2285, y = 635, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2286, y = 635, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2287, y = 1302, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2287, y = 1349, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2288, y = 1349, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2288, y = 297, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2290, y = 1386, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2293, y = 904, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2294, y = 1378, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2295, y = 146, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2296, y = 122, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2296, y = 1362, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2296, y = 642, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2299, y = 443, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2299, y = 565, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2301, y = 1022, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2304, y = 237, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2305, y = 311, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2305, y = 923, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2306, y = 576, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2309, y = 1053, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2312, y = 447, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2315, y = 574, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2316, y = 265, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2319, y = 256, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2319, y = 897, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2320, y = 1054, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2320, y = 148, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2321, y = 1072, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2322, y = 695, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2326, y = 411, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2329, y = 332, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 233, y = 2937, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2331, y = 232, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2333, y = 688, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2334, y = 688, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2334, y = 988, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2335, y = 687, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2336, y = 687, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2337, y = 313, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2337, y = 377, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2340, y = 339, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2346, y = 377, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2347, y = 1001, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2357, y = 671, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2357, y = 672, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2358, y = 403, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2359, y = 290, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2360, y = 290, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2362, y = 314, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2368, y = 247, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2388, y = 1025, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2389, y = 374, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 239, y = 2625, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 239, y = 2772, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2399, y = 1035, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2399, y = 325, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2408, y = 641, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2411, y = 1026, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2413, y = 610, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2423, y = 334, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2424, y = 740, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2426, y = 687, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 243, y = 2791, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2432, y = 212, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2432, y = 637, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2435, y = 721, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2436, y = 427, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2437, y = 329, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2437, y = 774, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2438, y = 654, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2438, y = 760, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2440, y = 794, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2442, y = 302, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2442, y = 784, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2443, y = 775, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2450, y = 1016, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2450, y = 435, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2451, y = 1138, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2451, y = 435, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2451, y = 765, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2451, y = 783, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2451, y = 784, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2453, y = 990, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2454, y = 675, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2458, y = 267, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2460, y = 290, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2462, y = 1108, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2463, y = 1108, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2469, y = 426, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2470, y = 981, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2472, y = 712, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2472, y = 771, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2473, y = 784, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2474, y = 690, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2475, y = 967, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2480, y = 374, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2482, y = 778, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2484, y = 389, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2485, y = 1112, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2485, y = 311, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2488, y = 292, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2498, y = 719, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2503, y = 385, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2504, y = 713, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2505, y = 370, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2509, y = 701, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 251, y = 2581, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2516, y = 1085, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2516, y = 1329, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2517, y = 968, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2524, y = 360, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2524, y = 369, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2528, y = 1338, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2535, y = 929, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2536, y = 980, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2537, y = 1332, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2540, y = 201, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2543, y = 912, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2549, y = 715, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2550, y = 345, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2551, y = 185, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2552, y = 922, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2553, y = 1339, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2553, y = 333, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2558, y = 138, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2565, y = 188, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2565, y = 252, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2567, y = 320, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2568, y = 988, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2569, y = 724, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2571, y = 955, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2572, y = 300, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2572, y = 955, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2575, y = 178, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2578, y = 830, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2579, y = 874, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2585, y = 1312, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2589, y = 1330, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2589, y = 851, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2589, y = 955, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2592, y = 719, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2597, y = 292, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2599, y = 143, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2601, y = 885, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2618, y = 268, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2622, y = 907, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2623, y = 181, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2624, y = 947, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2628, y = 239, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2631, y = 133, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2637, y = 257, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2638, y = 161, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2640, y = 223, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2640, y = 268, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2644, y = 962, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2652, y = 274, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 266, y = 2808, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2671, y = 944, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2674, y = 244, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2691, y = 974, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 270, y = 2664, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2701, y = 230, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2703, y = 214, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 271, y = 2586, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2712, y = 271, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2718, y = 969, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2731, y = 274, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2735, y = 834, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 274, y = 2688, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2749, y = 830, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2772, y = 906, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2800, y = 832, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2814, y = 892, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2830, y = 842, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 285, y = 2629, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 2872, y = 921, z = 0, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 297, y = 2810, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 298, y = 2681, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 309, y = 2762, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 313, y = 2670, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 352, y = 2498, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 362, y = 2561, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 372, y = 2465, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 375, y = 2528, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 378, y = 2584, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 405, y = 2604, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 408, y = 2503, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 440, y = 2465, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 450, y = 2657, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 589, y = 2997, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 640, y = 125, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 641, y = 122, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 647, y = 2957, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 650, y = 2983, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 651, y = 147, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 651, y = 2983, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 666, y = 2982, z = 2, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 719, y = 166, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 722, y = 167, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 723, y = 266, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 728, y = 264, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 733, y = 97, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 759, y = 154, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 759, y = 156, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 763, y = 197, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 772, y = 190, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 780, y = 128, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 788, y = 209, z = 1, stationary = false, aggressive = true)
@Spawn(type = "Goblin Scout", x = 795, y = 201, z = 1, stationary = false, aggressive = true)
public final class GoblinScout extends DataMonster {
  public static final String SOUND_ATTACK = "Whooshh 2.wav";
  public static final String SOUND_DEATH = "Goblin Dying.wav";
  public static final String SOUND_HIT = "Goblin Hit.wav";

  public static final String CANONICAL_NAME = "Goblin Scout";

  public GoblinScout(MonsterDef definition, float x, float y) throws GameException {

    super(definition, x, y);
  }

  @Override
  public String getCanonicalName() {

    return CANONICAL_NAME;
  }

  public static MonsterDef definition() {
    return new MonsterDef(
        "Goblin Scout",
        "${monster.goblin_scout}",
        132,
        0,
        2,
        136,
        7,
        17,
        30000L,
        "Goblin#l",
        "GoblinA#i",
        "GoblinC!o",
        SOUND_ATTACK,
        SOUND_DEATH,
        SOUND_HIT,
        14,
        44,
        java.util.List.of(
            new MonsterDef.LootDrop("Goblin leather armor", 0.004f),
            new MonsterDef.LootDrop("Leather belt", 0.01f),
            new MonsterDef.LootDrop("Light healing potion", 0.05f),
            new MonsterDef.LootDrop("Ring of light", 0.01f),
            new MonsterDef.LootDrop("Healing potion", 0.01f)),
        false,
        0.0f,
        23,
        22,
        22,
        24,
        0,
        22,
        0,
        new int[] {120, 60, 90, 90, 90, 5025, 100, 100, 100, 100, 100, 100},
        8,
        42,
        0,
        1074790400,
        20001,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        40,
        20,
        0,
        true,
        java.util.List.of(new MonsterDef.Attack("1d11+6", 106, 100, 0, 0, 0)),
        false,
        0,
        java.util.List.of(),
        java.util.Map.of());
  }
}
