package com.perso.T4C.monster;

import com.perso.T4C.exception.GameException;
import com.perso.T4C.monster.core.*;
import com.perso.T4C.spawn.Spawn;

@Spawn(type = "Horse", x = 2686, y = 971, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Horse", x = 2705, y = 1004, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Horse", x = 2722, y = 859, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Horse", x = 2740, y = 1047, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Horse", x = 2763, y = 982, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Horse", x = 2767, y = 952, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Horse", x = 2803, y = 954, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Horse", x = 2810, y = 998, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1021, y = 2095, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1023, y = 349, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1029, y = 1232, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1038, y = 1152, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1048, y = 2218, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1056, y = 1743, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1069, y = 2046, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1072, y = 1062, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1074, y = 105, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1075, y = 2403, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1082, y = 1298, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1084, y = 350, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1092, y = 2562, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1098, y = 1948, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1105, y = 1124, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1109, y = 1263, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1114, y = 2270, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1115, y = 2545, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1117, y = 1851, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1120, y = 194, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1126, y = 2465, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1130, y = 1979, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1132, y = 1104, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1133, y = 2433, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1137, y = 307, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1143, y = 2658, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1149, y = 2700, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1151, y = 1190, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1160, y = 1063, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1161, y = 2537, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1179, y = 1881, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1199, y = 1969, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1202, y = 2650, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1206, y = 1148, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1213, y = 2271, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1215, y = 2691, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1219, y = 2406, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1227, y = 2572, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1227, y = 2897, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1228, y = 2850, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1231, y = 2911, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1249, y = 1819, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1263, y = 1913, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1270, y = 2846, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1273, y = 2754, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1278, y = 2446, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1286, y = 2872, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1297, y = 2289, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1307, y = 2824, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1314, y = 2858, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1317, y = 2802, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 132, y = 658, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1322, y = 2509, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1323, y = 2779, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1340, y = 2483, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1353, y = 2690, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1363, y = 2902, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1370, y = 2885, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1371, y = 2534, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1373, y = 2678, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1373, y = 2736, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1374, y = 2735, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1401, y = 1838, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1402, y = 2720, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1501, y = 230, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1523, y = 2859, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1555, y = 1148, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1575, y = 2906, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1602, y = 1105, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1644, y = 2498, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1649, y = 2479, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1656, y = 2486, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1661, y = 2492, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 167, y = 1067, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1739, y = 1313, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1752, y = 1286, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1758, y = 1292, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1764, y = 1023, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1764, y = 1298, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1775, y = 1139, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1884, y = 1126, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1901, y = 1095, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 1915, y = 1185, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 195, y = 393, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2058, y = 1232, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2073, y = 1214, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2108, y = 1089, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2150, y = 1340, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2180, y = 1016, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2205, y = 1032, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2243, y = 386, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2258, y = 978, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2258, y = 986, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2259, y = 986, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2264, y = 221, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2288, y = 554, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2302, y = 1154, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2303, y = 147, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2314, y = 1234, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2316, y = 1247, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2318, y = 546, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2343, y = 1046, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2351, y = 251, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2357, y = 358, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2368, y = 840, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 237, y = 387, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2390, y = 833, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2415, y = 943, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2421, y = 954, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2425, y = 457, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2433, y = 1447, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2476, y = 1129, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2528, y = 1174, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2528, y = 1262, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 253, y = 1206, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2531, y = 565, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 255, y = 412, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2556, y = 1136, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2559, y = 431, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2562, y = 1202, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2565, y = 1179, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2565, y = 421, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2576, y = 147, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2583, y = 1184, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2584, y = 1136, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2588, y = 751, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2599, y = 996, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2603, y = 1217, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 263, y = 402, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2634, y = 1001, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2643, y = 155, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2654, y = 1256, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 266, y = 561, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2679, y = 449, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2683, y = 1116, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2686, y = 860, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2695, y = 563, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 271, y = 374, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2745, y = 405, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2759, y = 465, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2766, y = 121, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2766, y = 215, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 277, y = 442, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2805, y = 377, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2807, y = 239, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2811, y = 118, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2855, y = 219, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2878, y = 218, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2908, y = 179, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2934, y = 1158, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2940, y = 1164, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2943, y = 1166, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2948, y = 1172, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2953, y = 1177, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 2957, y = 1187, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 313, y = 1200, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 313, y = 997, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 343, y = 648, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 368, y = 1047, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 393, y = 1122, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 406, y = 570, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 415, y = 453, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 422, y = 208, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 460, y = 359, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 463, y = 892, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 465, y = 1211, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 469, y = 904, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 470, y = 938, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 475, y = 682, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 489, y = 872, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 492, y = 917, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 496, y = 2696, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 496, y = 898, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 502, y = 1164, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 516, y = 271, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 518, y = 909, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 519, y = 997, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 521, y = 884, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 526, y = 1051, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 532, y = 1823, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 538, y = 128, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 547, y = 1006, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 552, y = 1120, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 557, y = 1836, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 559, y = 965, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 579, y = 594, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 584, y = 896, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 588, y = 1089, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 590, y = 951, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 596, y = 907, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 604, y = 2454, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 609, y = 327, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 610, y = 1919, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 613, y = 733, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 618, y = 792, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 620, y = 1065, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 622, y = 168, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 624, y = 1071, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 624, y = 1724, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 631, y = 1048, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 645, y = 1012, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 646, y = 1547, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 654, y = 1692, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 654, y = 517, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 660, y = 1502, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 663, y = 898, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 665, y = 1935, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 668, y = 228, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 672, y = 830, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 673, y = 1647, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 674, y = 809, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 679, y = 295, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 687, y = 1104, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 691, y = 1547, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 699, y = 390, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 699, y = 777, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 704, y = 1688, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 706, y = 1045, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 708, y = 470, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 714, y = 1012, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 722, y = 1508, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 723, y = 921, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 728, y = 985, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 731, y = 823, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 746, y = 1819, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 748, y = 1030, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 749, y = 1097, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 749, y = 2469, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 770, y = 336, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 770, y = 723, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 774, y = 2701, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 779, y = 2718, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 781, y = 1604, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 783, y = 516, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 785, y = 2678, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 788, y = 1474, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 789, y = 439, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 790, y = 888, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 796, y = 2132, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 819, y = 1084, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 823, y = 2593, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 824, y = 550, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 830, y = 794, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 830, y = 845, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 839, y = 277, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 843, y = 467, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 849, y = 1585, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 850, y = 2422, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 851, y = 2498, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 855, y = 331, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 857, y = 1999, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 857, y = 2788, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 866, y = 1933, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 868, y = 1772, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 868, y = 880, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 870, y = 1721, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 871, y = 429, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 872, y = 914, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 874, y = 2106, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 876, y = 388, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 885, y = 1077, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 886, y = 1898, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 887, y = 1964, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 898, y = 2225, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 899, y = 732, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 905, y = 1984, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 921, y = 797, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 928, y = 2807, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 930, y = 2342, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 935, y = 2305, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 938, y = 2607, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 948, y = 272, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 951, y = 368, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 952, y = 1875, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 953, y = 748, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 957, y = 527, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 962, y = 2668, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 963, y = 2074, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 968, y = 1951, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 970, y = 1791, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 979, y = 2296, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 981, y = 2446, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 983, y = 601, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 983, y = 742, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 985, y = 1911, z = 0, stationary = false, aggressive = false)
@Spawn(type = "Wild Horse", x = 998, y = 359, z = 0, stationary = false, aggressive = false)
public final class r272WildHorse extends DataMonster {
  public static final String SOUND_ATTACK = "Pegase Attack.wav";
  public static final String SOUND_DEATH = "Pegase Dying.wav";
  public static final String SOUND_HIT = "Pegase Hit.wav";

  public r272WildHorse(MonsterDef definition, float worldX, float worldY) throws GameException {

    super(definition, worldX, worldY);
  }

  public static MonsterDef definition() {
    return new MonsterDef(
        "Wild Horse",
        "${monster.wild_horse}",
        353,
        0,
        0,
        0,
        0,
        0,
        30000L,
        "Horse#h",
        "HorseA",
        "HorseC#l",
        SOUND_ATTACK,
        SOUND_DEATH,
        SOUND_HIT,
        0,
        0,
        java.util.List.of(),
        false,
        0.0f,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        new int[] {56, 56, 56, 56, 56, 5000, 100, 100, 100, 100, 100, 100},
        20,
        90,
        0,
        1076101120,
        20022,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -100,
        13,
        0,
        false,
        java.util.List.of(),
        true,
        30,
        java.util.List.of("Horse"),
        java.util.Map.of());
  }
}
