package com.perso.T4C.monster;

import java.util.Map;
import com.perso.T4C.exception.GameException;
import com.perso.T4C.monster.core.DataMonster;
import com.perso.T4C.monster.core.MonsterDef;
import com.perso.T4C.spawn.Spawn;

@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1757, y = 1048, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1758, y = 1049, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1758, y = 951, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1759, y = 952, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1764, y = 1099, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1765, y = 1100, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1774, y = 1053, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1775, y = 1054, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1890, y = 992, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1891, y = 993, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1907, y = 994, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1908, y = 995, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1910, y = 1022, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1911, y = 1023, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1917, y = 1045, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1918, y = 1046, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1937, y = 1061, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 1938, y = 1062, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2480, y = 229, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2481, y = 230, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2488, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2488, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2488, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2489, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2490, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 589, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2491, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 589, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2492, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 589, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2493, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2494, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2495, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2497, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2497, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2496, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2497, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2510, y = 388, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2511, y = 389, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2519, y = 168, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2520, y = 169, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2533, y = 488, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2534, y = 489, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2538, y = 511, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2539, y = 512, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2545, y = 373, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2546, y = 374, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2547, y = 445, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2548, y = 446, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2556, y = 257, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2557, y = 258, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2561, y = 483, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2562, y = 484, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2565, y = 121, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2566, y = 122, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2578, y = 366, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2579, y = 367, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2583, y = 1336, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2584, y = 1337, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2589, y = 187, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2590, y = 188, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2598, y = 135, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2599, y = 136, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2606, y = 602, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2607, y = 603, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2621, y = 387, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2622, y = 388, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2628, y = 652, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2629, y = 653, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2635, y = 330, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2636, y = 331, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2641, y = 297, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2642, y = 298, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2653, y = 384, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2654, y = 385, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2684, y = 363, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 2685, y = 364, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 377, y = 347, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 378, y = 348, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 396, y = 330, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 397, y = 331, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 398, y = 417, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 399, y = 418, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 406, y = 438, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 407, y = 439, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 408, y = 404, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 409, y = 405, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 409, y = 307, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 410, y = 308, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 409, y = 327, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 410, y = 328, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 410, y = 366, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 411, y = 367, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 414, y = 374, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 415, y = 375, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 418, y = 285, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 419, y = 286, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 419, y = 390, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 420, y = 391, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 423, y = 170, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 424, y = 171, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 426, y = 128, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 427, y = 129, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 427, y = 250, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 428, y = 251, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 431, y = 403, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 432, y = 404, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 432, y = 388, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 433, y = 389, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 432, y = 464, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 433, y = 465, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 436, y = 350, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 437, y = 351, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 437, y = 182, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 438, y = 183, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 438, y = 442, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 439, y = 443, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 439, y = 157, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 440, y = 158, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 444, y = 281, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 445, y = 282, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 446, y = 294, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 447, y = 295, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 446, y = 339, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 447, y = 340, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 453, y = 324, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 454, y = 325, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 454, y = 456, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 455, y = 457, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 456, y = 296, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 457, y = 297, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 458, y = 217, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 459, y = 218, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 458, y = 240, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 459, y = 241, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 458, y = 373, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 459, y = 374, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 462, y = 150, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 463, y = 151, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 466, y = 413, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 467, y = 414, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 468, y = 253, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 469, y = 254, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 471, y = 332, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 472, y = 333, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 474, y = 197, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 475, y = 198, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 474, y = 350, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 475, y = 351, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 474, y = 365, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 475, y = 366, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 475, y = 404, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 476, y = 405, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 477, y = 212, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 478, y = 213, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 480, y = 385, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 481, y = 386, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 482, y = 169, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 483, y = 170, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 484, y = 302, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 485, y = 303, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 486, y = 316, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 487, y = 317, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 488, y = 427, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 489, y = 428, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 489, y = 137, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 490, y = 138, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 490, y = 279, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 491, y = 280, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 491, y = 370, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 492, y = 371, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 493, y = 164, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 494, y = 165, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 494, y = 229, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 495, y = 230, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 494, y = 352, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 495, y = 353, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 497, y = 254, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 498, y = 255, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 497, y = 411, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 498, y = 412, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 500, y = 320, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 501, y = 321, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 501, y = 140, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 502, y = 141, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 503, y = 284, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 504, y = 285, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 506, y = 209, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 507, y = 210, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 511, y = 166, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 512, y = 167, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 518, y = 176, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 519, y = 177, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 520, y = 311, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 521, y = 312, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 537, y = 283, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 538, y = 284, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 540, y = 293, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 541, y = 294, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 544, y = 430, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 545, y = 431, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 545, y = 270, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 546, y = 271, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 549, y = 149, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 550, y = 150, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 558, y = 345, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 559, y = 346, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 559, y = 295, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 560, y = 296, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 564, y = 120, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 565, y = 121, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 570, y = 158, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 571, y = 159, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 576, y = 388, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 577, y = 389, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 579, y = 365, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 580, y = 366, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 583, y = 338, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 584, y = 339, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 590, y = 309, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 591, y = 310, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 591, y = 166, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 592, y = 167, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 601, y = 172, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 602, y = 173, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 604, y = 110, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 605, y = 111, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 615, y = 142, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 616, y = 143, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 625, y = 299, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 626, y = 300, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 626, y = 185, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 627, y = 186, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 626, y = 217, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 627, y = 218, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 627, y = 336, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 628, y = 337, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 637, y = 207, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 638, y = 208, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 640, y = 355, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 641, y = 356, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 644, y = 153, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 645, y = 154, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 644, y = 245, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 645, y = 246, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 648, y = 317, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 649, y = 318, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 650, y = 300, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 651, y = 301, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 657, y = 185, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 658, y = 186, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 658, y = 274, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 659, y = 275, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 663, y = 130, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 664, y = 131, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 665, y = 162, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 666, y = 163, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 665, y = 261, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 666, y = 262, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 685, y = 243, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 686, y = 244, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 691, y = 144, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 692, y = 145, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 691, y = 262, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 692, y = 263, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 691, y = 304, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 692, y = 305, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 692, y = 120, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 693, y = 121, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 693, y = 216, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 694, y = 217, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 700, y = 184, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 701, y = 185, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 702, y = 234, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 703, y = 235, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 704, y = 255, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 705, y = 256, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 722, y = 270, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 723, y = 271, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 761, y = 144, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 762, y = 145, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 817, y = 100, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 818, y = 101, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 825, y = 159, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 826, y = 160, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 846, y = 113, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGGRUBBRINGAH", x = 847, y = 114, z = 0, stationary = false, aggressive = true)
public final class SKRAUGGRUBBRINGAH extends DataMonster {
  public static final String SOUND_ATTACK = "Skraug Attack.wav";
  public static final String SOUND_DEATH = "Skraug Die.wav";
  public static final String SOUND_HIT = "Taunting Hit.wav";

  public SKRAUGGRUBBRINGAH(MonsterDef definition, float worldX, float worldY) throws GameException {

    super(definition, worldX, worldY);
  }

  public static MonsterDef definition() {
    return new MonsterDef(
        "SKRAUGGRUBBRINGAH",
        "${monster.skrauggrubbringah}",
        906,
        0,
        38,
        17480,
        45,
        102,
        30000L,
        "64kSkavenPeon#i",
        "64kSkavenPeonA#j",
        "64kSkavenPeonC!t",
        SOUND_ATTACK,
        SOUND_DEATH,
        SOUND_HIT,
        75,
        231,
        java.util.List.of(
            new MonsterDef.LootDrop("blade_of_heroism", 0.3f),
            new MonsterDef.LootDrop("moon_tug_scalp", 0.3f),
            new MonsterDef.LootDrop("raw_crystal", 0.3f)),
        false,
        0.0f,
        57,
        52,
        52,
        65,
        52,
        52,
        23,
        new int[] {74, 74, 74, 74, 74, 5000, 100, 100, 100, 100, 100, 100},
        42,
        178,
        0,
        1101529088,
        20059,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        100,
        0,
        0,
        true,
        java.util.List.of(new MonsterDef.Attack("1d58+44", 514, 100, 0, 0, 0)),
        false,
        0,
        java.util.List.of(),
        java.util.Map.of());
  }
}
