package com.perso.T4C.monster;

import java.util.Map;
import com.perso.T4C.exception.GameException;
import com.perso.T4C.monster.core.DataMonster;
import com.perso.T4C.monster.core.MonsterDef;
import com.perso.T4C.monster.core.MonsterGoldCurve;
import com.perso.T4C.spawn.Spawn;

@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1002, y = 557, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1003, y = 558, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1003, y = 451, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1004, y = 452, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1004, y = 531, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1005, y = 532, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1005, y = 477, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1006, y = 478, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1011, y = 541, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1012, y = 542, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1013, y = 508, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1014, y = 509, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1013, y = 588, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1014, y = 589, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1017, y = 465, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1018, y = 466, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1017, y = 609, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1018, y = 610, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1018, y = 566, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1019, y = 567, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1019, y = 492, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1020, y = 493, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1030, y = 658, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1031, y = 659, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1031, y = 626, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1032, y = 627, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1036, y = 488, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1037, y = 489, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1041, y = 655, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1042, y = 656, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1049, y = 431, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1050, y = 432, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1056, y = 450, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1057, y = 451, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1082, y = 429, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1083, y = 430, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1130, y = 413, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1131, y = 414, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1134, y = 449, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1135, y = 450, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1134, y = 468, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1135, y = 469, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1180, y = 407, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1181, y = 408, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1193, y = 547, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1194, y = 548, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1260, y = 460, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1261, y = 461, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1266, y = 532, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1267, y = 533, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1340, y = 542, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1341, y = 543, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1932, y = 1372, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1933, y = 1373, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1945, y = 1358, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 1946, y = 1359, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2031, y = 1473, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2032, y = 1474, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2032, y = 1473, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2033, y = 1474, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2074, y = 1505, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2075, y = 1506, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2121, y = 1403, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2122, y = 1404, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2123, y = 1382, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2124, y = 1383, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2129, y = 1347, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2130, y = 1348, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2372, y = 1475, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2373, y = 1476, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2400, y = 1422, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2401, y = 1423, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2425, y = 1431, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2426, y = 1432, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2437, y = 1311, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2438, y = 1312, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2451, y = 1289, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2452, y = 1290, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2456, y = 1341, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2457, y = 1342, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2458, y = 1421, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2459, y = 1422, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2462, y = 1399, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2463, y = 1400, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2506, y = 1347, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2507, y = 1348, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2507, y = 1312, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2508, y = 1313, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2511, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2511, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2511, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2512, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2513, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2514, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 599, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2515, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 599, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 590, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2516, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 599, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2517, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 591, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 592, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2518, y = 597, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 598, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 593, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2520, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 594, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2520, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2519, y = 595, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2520, y = 596, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2528, y = 1471, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2529, y = 1472, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2534, y = 1512, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2535, y = 1513, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2556, y = 1485, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2557, y = 1486, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2558, y = 1345, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2559, y = 1346, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2573, y = 1370, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2574, y = 1371, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2592, y = 1470, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2593, y = 1471, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2598, y = 415, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2599, y = 416, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2634, y = 587, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2635, y = 588, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2636, y = 631, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2637, y = 632, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2641, y = 1455, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2642, y = 1456, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2663, y = 401, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2664, y = 402, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2692, y = 677, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2693, y = 678, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2716, y = 387, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2717, y = 388, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2769, y = 513, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2770, y = 514, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2787, y = 625, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2788, y = 626, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2795, y = 683, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2796, y = 684, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2816, y = 605, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2817, y = 606, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2826, y = 677, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2827, y = 678, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2834, y = 380, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2835, y = 381, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2837, y = 437, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2838, y = 438, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2846, y = 566, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2847, y = 567, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2853, y = 355, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2854, y = 356, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2870, y = 652, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2871, y = 653, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2903, y = 623, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2904, y = 624, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2915, y = 522, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 2916, y = 523, z = 2, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 747, y = 557, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 748, y = 558, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 767, y = 533, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 768, y = 534, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 772, y = 454, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 773, y = 455, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 782, y = 493, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 783, y = 494, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 792, y = 478, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 793, y = 479, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 804, y = 459, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 805, y = 460, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 824, y = 507, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 825, y = 508, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 827, y = 447, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 828, y = 448, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 827, y = 570, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 828, y = 571, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 833, y = 472, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 834, y = 473, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 851, y = 443, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 852, y = 444, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 857, y = 489, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 858, y = 490, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 868, y = 527, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 869, y = 528, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 872, y = 510, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 873, y = 511, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 876, y = 416, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 877, y = 417, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 880, y = 480, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 881, y = 481, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 883, y = 465, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 884, y = 466, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 887, y = 430, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 888, y = 431, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 895, y = 575, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 896, y = 576, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 902, y = 442, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 903, y = 443, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 905, y = 509, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 906, y = 510, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 913, y = 434, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 914, y = 435, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 914, y = 396, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 915, y = 397, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 915, y = 541, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 916, y = 542, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 920, y = 494, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 921, y = 495, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 923, y = 414, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 924, y = 415, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 925, y = 469, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 926, y = 470, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 934, y = 420, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 935, y = 421, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 936, y = 472, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 937, y = 473, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 940, y = 549, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 941, y = 550, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 949, y = 451, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 950, y = 452, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 952, y = 469, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 953, y = 470, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 959, y = 493, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 960, y = 494, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 964, y = 613, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 965, y = 614, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 968, y = 455, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 969, y = 456, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 974, y = 477, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 975, y = 478, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 982, y = 438, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 983, y = 439, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 990, y = 464, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 991, y = 465, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 990, y = 546, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 991, y = 547, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 992, y = 568, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 993, y = 569, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 993, y = 598, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 994, y = 599, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 996, y = 515, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 997, y = 516, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 997, y = 495, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 998, y = 496, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 998, y = 647, z = 0, stationary = false, aggressive = true)
@Spawn(type = "SKRAUGMUNCHHUNTOR", x = 999, y = 648, z = 0, stationary = false, aggressive = true)
public final class SKRAUGMUNCHHUNTOR extends DataMonster {
  public static final String SOUND_ATTACK = "Skraug Attack.wav";
  public static final String SOUND_DEATH = "Skraug Die.wav";
  public static final String SOUND_HIT = "Taunting Hit.wav";

  public SKRAUGMUNCHHUNTOR(MonsterDef definition, float worldX, float worldY) throws GameException {

    super(definition, worldX, worldY);
  }

  public static MonsterDef definition() {
    return new MonsterDef(
        "SKRAUGMUNCHHUNTOR",
        "${monster.skraugmunchhuntor}",
        966,
        0,
        26,
        12870,
        48,
        109,
        30000L,
        "64kSkavenPeon#i",
        "64kSkavenPeonA#j",
        "64kSkavenPeonC!t",
        SOUND_ATTACK,
        SOUND_DEATH,
        SOUND_HIT,
        MonsterGoldCurve.goldMin(150),
        MonsterGoldCurve.goldMax(150),
        java.util.List.of(
            new MonsterDef.LootDrop("blade_of_heroism", 0.3f),
            new MonsterDef.LootDrop("moon_tug_scalp", 0.3f),
            new MonsterDef.LootDrop("raw_crystal", 0.3f)),
        false,
        0.0f,
        59,
        54,
        54,
        67,
        54,
        54,
        23,
        new int[] {73, 73, 73, 73, 73, 5000, 100, 100, 100, 100, 100, 100},
        150,
        186,
        0,
        1102053376,
        20047,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        100,
        0,
        0,
        true,
        java.util.List.of(new MonsterDef.Attack("1d62+47", 538, 100, 0, 0, 0)),
        false,
        0,
        java.util.List.of(),
        java.util.Map.of());
  }
}
