package com.perso.T4C.npc.catalog;

import com.perso.T4C.npc.behavior.NpcBehavior;
import com.perso.T4C.npc.behavior.ShopBehavior;
import java.util.List;
import java.util.Map;

public final class ShopCatalog {
  public static final String SOUND_ATTACK = "Whooshh 1.wav";
  public static final String SOUND_DEATH = "Male Dying 1.wav";
  public static final String SOUND_HIT = "Male Hit 1.wav";

  private static final List<String> POTIONS =
      List.of(
          "torch",
          "light_healing_potion",
          "potion_of_mana",
          "healing_potion",
          "serious_healing_potion",
          "mana_elixir");

  private static final List<String> FALI =
      List.of(
          "apple",
          "torch",
          "light_healing_potion",
          "potion_of_mana",
          "healing_potion",
          "iron_ring",
          "item.mana_prism",
          "item.critical_healing_potion");

  private static final List<String> CHRYSEIDA =
      List.of(
          "torch",
          "light_healing_potion",
          "healing_potion",
          "serious_healing_potion",
          "potion_of_mana",
          "mana_elixir",
          "item.mana_prism",
          "item.critical_healing_potion",
          "potion_of_cure_rabies",
          "scroll_of_lighthaven",
          "scroll_of_windhowl",
          "scroll_of_silversky",
          "scroll_of_stonecrest",
          "symbol_of_hope",
          "mandrake",
          "acolytes_tarnished_locket",
          "sunken_vestment");

  private static final List<String> KARAHN =
      List.of(
          "rusted_short_sword_1",
          "rusted_long_sword_1",
          "polished_short_sword_1",
          "polished_long_sword_1",
          "polished_broadsword_1",
          "rusted_hand_axe_1",
          "polished_hand_axe_1",
          "rusted_dirk_1",
          "rusted_dagger_1",
          "polished_dirk_1",
          "polished_dagger_1",
          "wooden_club_1",
          "steel_reinforced_club_1",
          "steel_reinforced_warhammer_1",
          "fine_steel_warhammer_1",
          "wooden_staff_1",
          "iron_staff_1",
          "quarterstaff_1",
          "staff_of_thorns_1",
          "ashwood_flatbow_1",
          "ashwood_longbow_1",
          "ashwood_reflex_bow_1",
          "elm_flatbow_1",
          "elm_longbow_1",
          "elm_reflex_bow_1",
          "elm_recurve_bow_1");

  private static final List<String> SEBAN =
      KARAHN.stream().map(s -> s.replace("_1", "_2")).toList();

  private static final List<String> RAWLIN =
      List.of(
          "fine_steel_short_sword_1",
          "fine_steel_long_sword_1",
          "fine_steel_broadsword_1",
          "fine_steel_scimitar_1",
          "fine_steel_scimitar1_dual",
          "high_metal_short_sword_1",
          "fine_steel_hand_axe_1",
          "fine_steel_hand_axe1_dual",
          "fine_steel_battle_axe_1",
          "fine_steel_dagger_1",
          "fine_steel_dagger1_dual",
          "high_metal_dagger_1",
          "fine_steel_mace_1",
          "fine_steel_mace1_dual",
          "high_metal_mace_1",
          "high_metal_flail_1",
          "bo_1",
          "rang_kwan_1",
          "tetsubo_1",
          "hickory_flatbow_1",
          "hickory_longbow_1",
          "hickory_reflex_bow_1",
          "hickory_recurve_bow_1",
          "hickory_compound_bow_1");

  private static final List<String> RHODAR =
      List.of(
          "fine_steel_short_sword",
          "fine_steel_long_sword",
          "fine_steel_broadsword",
          "fine_steel_scimitar",
          "fine_steel_scimitar_dual",
          "high_metal_short_sword",
          "fine_steel_hand_axe",
          "fine_steel_hand_axe_dual",
          "fine_steel_battle_axe",
          "fine_steel_dagger",
          "fine_steel_dagger_dual",
          "high_metal_dagger",
          "hickory_flatbow",
          "hickory_longbow",
          "hickory_reflex_bow",
          "hickory_recurve_bow",
          "hickory_compound_bow",
          "bone_tipped_arrow");

  private static final List<String> GULFRID =
      List.of(
          "high_metal_long_sword",
          "high_metal_broadsword",
          "high_metal_scimitar",
          "high_metal_bastard_sword",
          "high_metal_bastard_sword_dual",
          "high_metal_hand_axe",
          "high_metal_battle_axe",
          "mithril_dagger",
          "mithril_blade",
          "mithril_blade_dual",
          "mithril_flail",
          "oak_flatbow",
          "oak_longbow",
          "oak_reflex_bow",
          "oak_recurve_bow",
          "oak_compound_bow",
          "oak_composite_bow",
          "flight_arrow");

  private static final List<String> THOR =
      List.of(
          "high_metal_long_sword_1",
          "high_metal_broadsword_1",
          "high_metal_scimitar_1",
          "high_metal_bastard_sword_1",
          "high_metal_bastard_sword1_dual",
          "high_metal_hand_axe_1",
          "high_metal_battle_axe_1",
          "mithril_dagger_1",
          "mithril_blade_1",
          "mithril_blade1_dual",
          "mithril_flail_1",
          "high_metal_long_sword_2",
          "high_metal_broadsword_2",
          "high_metal_scimitar_2",
          "high_metal_bastard_sword_2",
          "high_metal_bastard_sword2_dual",
          "high_metal_hand_axe_2",
          "high_metal_battle_axe_2",
          "mithril_dagger_2",
          "mithril_blade_2",
          "mithril_blade2_dual",
          "mithril_flail_2",
          "oak_flatbow_1",
          "oak_longbow_1",
          "oak_reflex_bow_1",
          "oak_recurve_bow_1",
          "oak_compound_bow_1",
          "oak_composite_bow_1",
          "oak_flatbow_2",
          "oak_longbow_2",
          "oak_reflex_bow_2",
          "oak_recurve_bow_2",
          "oak_compound_bow_2",
          "oak_composite_bow_2");

  private static final List<String> LORD =
      List.of(
          "cedar_longbow_1",
          "cedar_longbow_2",
          "cedar_reflex_bow",
          "cedar_reflex_bow_1",
          "cedar_reflex_bow_2",
          "cedar_recurve_bow",
          "cedar_recurve_bow_1",
          "cedar_recurve_bow_2",
          "cedar_compound_bow",
          "cedar_compound_bow_1",
          "cedar_compound_bow_2",
          "cedar_composite_bow",
          "cedar_composite_bow_1",
          "cedar_composite_bow_2",
          "cedar_composite_bow_3",
          "lancewood_reflex_bow",
          "lancewood_reflex_bow_1",
          "lancewood_reflex_bow_2",
          "lancewood_recurve_bow",
          "lancewood_recurve_bow_1",
          "lancewood_recurve_bow_2",
          "lancewood_compound_bow",
          "lancewood_compound_bow_1",
          "lancewood_compound_bow_2",
          "lancewood_composite_bow",
          "lancewood_composite_bow_1",
          "lancewood_composite_bow_2",
          "lancewood_composite_bow_3",
          "black_locust_recurve_bow",
          "black_locust_recurve_bow_1",
          "black_locust_recurve_bow_2",
          "black_locust_compound_bow",
          "black_locust_compound_bow_1",
          "black_locust_compound_bow_2",
          "black_locust_composite_bow",
          "black_locust_composite_bow_1",
          "black_locust_composite_bow_2",
          "black_locust_composite_bow_4",
          "black_locust_composite_bow_5",
          "mithril_morningstar_1",
          "mithril_morningstar_2",
          "mithril_morningstar_3",
          "ancient_morningstar",
          "ancient_morningstar_1",
          "ancient_morningstar_2",
          "high_metal_broad_axe",
          "high_metal_broad_axe_1",
          "high_metal_broad_axe_2",
          "high_metal_broad_axe_3",
          "mithril_battle_axe",
          "mithril_battle_axe_1",
          "mithril_battle_axe_2",
          "mithril_broad_axe",
          "mithril_broad_axe_1",
          "mithril_broad_axe_2",
          "mithril_broad_axe_3",
          "ancient_broad_axe",
          "ancient_broad_axe_1",
          "ancient_broad_axe_2",
          "mithril_long_sword",
          "mithril_long_sword_1",
          "mithril_long_sword_2",
          "mithril_broadsword",
          "mithril_broadsword_1",
          "mithril_broadsword_2",
          "mithril_scimitar",
          "mithril_scimitar_1",
          "mithril_scimitar_2",
          "mithril_bastard_sword",
          "mithril_bastard_sword_1",
          "mithril_bastard_sword_2",
          "mithril_two_handed_sword",
          "mithril_two_handed_sword_1",
          "mithril_two_handed_sword_2",
          "mithril_two_handed_sword_3",
          "mithril_two_handed_sword_4",
          "mithril_two_handed_sword_5",
          "adamantite_broadsword",
          "adamantite_broadsword_1",
          "adamantite_broadsword_2",
          "adamantite_scimitar",
          "adamantite_scimitar_1",
          "adamantite_scimitar_2",
          "adamantite_bastard_sword",
          "adamantite_bastard_sword_1",
          "adamantite_bastard_sword_2",
          "adamantite_two_handed_sword",
          "adamantite_two_handed_sword_1",
          "adamantite_two_handed_sword_2",
          "adamantite_two_handed_sword_3",
          "adamantite_two_handed_sword_4",
          "adamantite_two_handed_sword_5",
          "ancient_scimitar",
          "ancient_scimitar_1",
          "ancient_scimitar_2",
          "ancient_bastard_sword",
          "ancient_bastard_sword_1",
          "ancient_bastard_sword_2",
          "ancient_two_handed_sword",
          "ancient_two_handed_sword_1",
          "ancient_two_handed_sword_2",
          "adamantite_blade",
          "adamantite_blade_1",
          "adamantite_blade_2",
          "adamantite_blade_3",
          "ancient_blade",
          "ancient_blade_dual",
          "ancient_blade_1",
          "ancient_blade1_dual",
          "ancient_blade_2",
          "ancient_blade2_dual",
          "ancient_blade_3",
          "ancient_blade3_dual",
          "mithril_shield",
          "gothic_shield",
          "adamantite_shield",
          "adamantite_shield_3",
          "adamantite_shield_4",
          "adamantite_shield_5",
          "adamantite_platemail_armor",
          "adamantite_plate_protector",
          "adamantite_platemail_gauntlets",
          "adamantite_platemail_helmet",
          "adamantite_platemail_leggings",
          "adamantite_platemail_boots");

  private static final Map<String, List<String>> M =
      Map.ofEntries(
          Map.entry("Fali", POTIONS),
          Map.entry("Boreas", POTIONS),
          Map.entry(
              "ChryseidaYolangda",
              List.of(
                  "torch",
                  "light_healing_potion",
                  "healing_potion",
                  "serious_healing_potion",
                  "potion_of_mana")),
          Map.entry(
              "Yolak",
              List.of(
                  "torch",
                  "light_healing_potion",
                  "potion_of_mana",
                  "healing_potion",
                  "scroll_of_lighthaven")),
          Map.entry(
              "TtayhMark",
              List.of(
                  "light_healing_potion",
                  "ring_of_light",
                  "ring_of_confidence",
                  "mana_elixir",
                  "leather_belt_of_survival")),
          Map.entry("RylethCth", List.of("plain_blank_scroll")),
          Map.entry(
              "OmarHald",
              List.of(
                  "ring_of_the_adept", "ring_of_the_healer", "ring_of_the_priest", "templar_ring")),
          Map.entry("Karahn", KARAHN),
          Map.entry("SebanForgelot", SEBAN),
          Map.entry("GulfridSteelhammer", GULFRID),
          Map.entry("LordoftheShops", LORD),
          Map.entry("ThorGlarefire", THOR),
          Map.entry("Rawlin", RAWLIN),
          Map.entry("RhodarHeatforge", RHODAR),
          Map.entry(
              "Taliron",
              List.of(
                  "red_cape",
                  "studded_leather_belt",
                  "studded_leather_gloves",
                  "studded_leather_helmet",
                  "studded_leather_pants",
                  "studded_leather_boots",
                  "studded_leather_armor",
                  "ringmail_girdle",
                  "ringmail_armor",
                  "ringmail_gauntlets",
                  "ringmail_helmet",
                  "ringmail_leggings",
                  "ringmail_boots",
                  "chainmail_girdle",
                  "chainmail",
                  "chainmail_gloves",
                  "chainmail_coif",
                  "chainmail_leggings",
                  "chainmail_boots",
                  "round_shield",
                  "large_shield")),
          Map.entry(
              "Gwen",
              List.of(
                  "cloth_pants",
                  "cloth_vest",
                  "leather_belt",
                  "leather_gloves",
                  "leather_helmet",
                  "leather_pants",
                  "leather_boots",
                  "leather_armor",
                  "red_cape",
                  "studded_leather_belt",
                  "studded_leather_gloves",
                  "studded_leather_helmet",
                  "studded_leather_pants",
                  "studded_leather_boots",
                  "studded_leather_armor",
                  "wooden_shield",
                  "round_shield")),
          Map.entry(
              "HerewaldIronbender",
              List.of(
                  "chainmail",
                  "chainmail_gloves",
                  "chainmail_coif",
                  "chainmail_girdle",
                  "chainmail_leggings",
                  "chainmail_boots",
                  "scale_mail",
                  "scalemail_gauntlets",
                  "scalemail_helmet",
                  "scalemail_protector",
                  "scalemail_leggings",
                  "scalemail_boots",
                  "large_shield",
                  "tower_shield")),
          Map.entry(
              "Kiadus",
              List.of(
                  "fine_steel_mace",
                  "fine_steel_mace_dual",
                  "high_metal_mace",
                  "high_metal_flail",
                  "bo",
                  "rang_kwan",
                  "tetsubo")),
          Map.entry(
              "NafuhrBloodhammer",
              List.of(
                  "red_cape",
                  "studded_leather_belt",
                  "studded_leather_gloves",
                  "studded_leather_helmet",
                  "studded_leather_pants",
                  "studded_leather_boots",
                  "studded_leather_armor",
                  "ringmail_girdle",
                  "ringmail_armor",
                  "ringmail_gauntlets",
                  "ringmail_helmet",
                  "ringmail_leggings",
                  "ringmail_boots",
                  "chainmail_girdle",
                  "chainmail",
                  "chainmail_gloves",
                  "chainmail_coif",
                  "chainmail_leggings",
                  "chainmail_boots",
                  "round_shield",
                  "large_shield")),
          Map.entry(
              "Sigfried",
              List.of(
                  "rusted_short_sword",
                  "rusted_long_sword",
                  "rusted_hand_axe",
                  "rusted_dirk",
                  "rusted_dagger",
                  "wooden_club",
                  "steel_reinforced_club",
                  "wooden_staff",
                  "iron_staff",
                  "ashwood_flatbow",
                  "ashwood_longbow",
                  "ashwood_reflex_bow",
                  "wooden_arrow")),
          Map.entry(
              "Rolph",
              List.of(
                  "cloth_pants",
                  "cloth_vest",
                  "leather_belt",
                  "leather_gloves",
                  "leather_helmet",
                  "leather_pants",
                  "leather_boots",
                  "leather_armor",
                  "red_cape",
                  "studded_leather_belt",
                  "studded_leather_gloves",
                  "studded_leather_helmet",
                  "studded_leather_pants",
                  "studded_leather_boots",
                  "studded_leather_armor",
                  "wooden_shield")),
          Map.entry(
              "WitchDoctorKwarlgloth",
              List.of(
                  "torch",
                  "light_healing_potion",
                  "healing_potion",
                  "serious_healing_potion",
                  "potion_of_mana")),
          Map.entry(
              "QuartermasterElenna",
              List.of(
                  "mithril_long_sword",
                  "mithril_blade",
                  "mithril_flail",
                  "mithril_battle_axe",
                  "mithril_broadsword",
                  "mithril_scimitar",
                  "mithril_bastard_sword",
                  "mithril_two_handed_sword",
                  "adamantite_broadsword",
                  "adamantite_scimitar",
                  "oak_composite_bow",
                  "cedar_composite_bow",
                  "large_shield",
                  "tower_shield")),
          Map.entry(
              "WayfarerBryndis",
              List.of(
                  "torch",
                  "light_healing_potion",
                  "healing_potion",
                  "serious_healing_potion",
                  "potion_of_mana",
                  "item.mana_prism",
                  "item.critical_healing_potion",
                  "scroll_of_avalon",
                  "scroll_of_lighthaven",
                  "symbol_of_hope")));

  public static NpcBehavior get(String id) {

    if ("WitchDoctorKwarlgloth".equals(id))
      return new ShopBehavior(
          List.of(
              "torch",
              "light_healing_potion",
              "healing_potion",
              "serious_healing_potion",
              "potion_of_mana",
              "mana_elixir",
              "manastone"));

    List<String> i =
        "Fali".equals(id) ? FALI : "ChryseidaYolangda".equals(id) ? CHRYSEIDA : M.get(id);

    if ("Boreas".equals(id)
        || "Yolak".equals(id)
        || "TtayhMark".equals(id)
        || "Kiadus".equals(id)
        || "RhodarHeatforge".equals(id)
        || "GulfridSteelhammer".equals(id)) return null;

    return i == null ? null : new ShopBehavior(i);
  }
}
